### ISSUE TITLE
[gatsby-theme-minimal-blog]: Code blocks do not use syntax highlighting, titles, etc

### ISSUE THREAD

**Issue by tombrereton** [LekoArts/gatsby-themes#1017]
Firstly, thanks for making this awesome theme. I'm really enjoying it.

## Description
The code blocks are not using syntax highlighting (the colours), or the titles, or anything else. They just appear as plain grey blocks

An example of the code block examples post is shown below.
<img width="996" alt="CleanShot 2022-10-13 at 17 01 55@2x" src="https://user-images.githubusercontent.com/12275517/195514559-03761ae2-007d-4efa-ac4f-456b41862c6f.png">

### Steps to reproduce

1. `npx gatsby new gatsby-starter-minimal-blog https://github.com/LekoArts/gatsby-starter-minimal-blog`
2. `cd gatsby-starter-minimal-blog`
3. `npm run develop`
4. Then navigate to the code block examples page: `http://localhost:8001/code-block-examples`

You should see the code block with only plain grey syntax highlighting.

### Expected result

Colours syntax highlighting, code title blocks, etc

### Actual result

No syntax highlight, no title blocks, etc

### Environment
```
  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 102.0.1
    Safari: 16.0
  npmPackages:
    gatsby: ^4.24.1 => 4.24.3
    gatsby-plugin-feed: ^4.24.0 => 4.24.0
    gatsby-plugin-image: ^2.24.0 => 2.24.0
    gatsby-plugin-manifest: ^4.24.0 => 4.24.0
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0
    gatsby-plugin-sitemap: ^5.24.0 => 5.24.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.27 => 1.1.27
    gatsby-source-filesystem: ^4.24.0 => 4.24.0
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

**Comment by LekoArts** [comment]
Thanks! Please remove your `node_modules`, the lock file and reinstall again. It should work now.

**Comment by tombrereton** [comment]
Working :) Thanks for such a quick fix.
