### ISSUE TITLE
[minimal blog]: initialColorModeName value set to light cause the code-block theme mistake

### ISSUE THREAD

**Issue by aaftio** [LekoArts/gatsby-themes#1059]
## Description

First open website when the browser's CSS media feature prefers-color-scheme is dark, the code-block will load the light theme.

### Steps to reproduce

1. Turn the browser `prefers-color-scheme` to `dark` ([Follow this instruction](https://stackoverflow.com/a/59223868))
2. Open the [page](https://minimal-blog.lekoarts.de/code-block-examples), and then `Ctrl + R` refresh the page.
3. Will see the website is in dark theme but the code-block is in light theme.
 
### Expected result

The code-block theme follow the website theme

### Actual result

The code-block theme do not follow the website theme

### Environment

The code run on the https://minimal-blog.lekoarts.de has the problem, so the environment is not the matter.

### My discovery

When run at develop mode `gatsby develop` this bug will not exists, I am not a Front-end development engineer, so I am not sure what exactly happened.

Thank you for your work on the wonderful theme again!

**Comment by LekoArts** [comment]
I'm pretty sure this happens because during `gatsby build` prism-react-renderer uses the light theme for its rendering and thus the HTML has the light theme tokens included (https://github.com/LekoArts/gatsby-themes/blob/main/themes/gatsby-theme-minimal-blog/src/components/code.tsx)

Using CSS Variables for the code block tokens should fix it. Had the same problem on my site: https://github.com/LekoArts/portfolio-v2/pull/62

**Comment by aaftio** [comment]
> I'm pretty sure this happens because during `gatsby build` prism-react-renderer uses the light theme for its rendering and thus the HTML has the light theme tokens included (https://github.com/LekoArts/gatsby-themes/blob/main/themes/gatsby-theme-minimal-blog/src/components/code.tsx)
> 
> Using CSS Variables for the code block tokens should fix it. Had the same problem on my site: [LekoArts/portfolio-v2#62](https://github.com/LekoArts/portfolio-v2/pull/62)

So the plan to fix is create `prism-react-renderer` themes in the gatsby-theme-minimal-blog project, am I right?
