### ISSUE TITLE
[minimal blog]: Code block copy button and language tag move with scroll

### ISSUE THREAD

**Issue by aaftio** [LekoArts/gatsby-themes#1060]
## Description

When the code line is longer enough, code block can scroll, when scroll it to right, the `Copy` button and language tag will move follow the scroll.

### Steps to reproduce

1. Write a long code line make the code block can scroll
2. Scroll the code block

![Code-Block](https://user-images.githubusercontent.com/1856880/204700773-57dced32-b6cf-40f4-adb5-7d49c02e04d1.gif)

### Expected result

The  `Copy` button and language tag don't move.

### Actual result

The `Copy` button and language tag will move follow the scroll.

### Environment

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    gatsby: ^4.24.1 => 4.24.4 
    gatsby-plugin-feed: ^4.24.0 => 4.24.0 
    gatsby-plugin-google-gtag: ^4.24.0 => 4.24.0 
    gatsby-plugin-manifest: ^4.24.0 => 4.24.0 
    gatsby-plugin-next-seo: ^1.10.0 => 1.10.0 
    gatsby-plugin-sitemap: ^5.24.0 => 5.24.0 
    gatsby-plugin-theme-ui: ^0.15.3 => 0.15.3 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.27 => 1.1.30 
    gatsby-remark-autolink-headers: ^5.24.0 => 5.24.0

**Comment by LekoArts** [comment]
This doesn't happen on https://minimal-blog.lekoarts.de/code-block-examples, please share a reproduction of your problem (e.g. a GitHub repository)

**Comment by aaftio** [comment]
I am using `@lekoarts/gatsby-theme-minimal-blog": "^5.0.1"`，and this [commit](https://github.com/LekoArts/gatsby-themes/commit/2d8e5d178bead2c9589ff0176982b6af18d2e62c) already fix the problem, maybe I need to upgrade my dependences. Thank you.
