### ISSUE TITLE
[*]: Make copyright overrideable

### ISSUE THREAD

**Issue by halkeye** [LekoArts/gatsby-themes#1131]
## Description

copyright notice is always current year. copyright notice should be when the copyright happens, [so time of creation](https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated), or last update, not current year.

### Steps to reproduce

Use any of the templates, like https://minimal-blog.lekoarts.de/

### Expected result

copyright should be posted year

### Actual result

© 2023 by Minimal Blog. All rights reserved.

### Environment

```
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.asdf/installs/nodejs/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.12.1/.npm/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Languages:
    Python: 3.10.2 - /home/halkeye/.asdf/shims/python
  Browsers:
    Chrome: 108.0.5359.124
  npmPackages:
    gatsby: ^5.5.0 => 5.5.0
    gatsby-plugin-feed: ^5.5.0 => 5.5.0
    gatsby-plugin-manifest: ^5.5.0 => 5.5.0
    gatsby-plugin-mdx-embed: ^1.1.3 => 1.1.3
    gatsby-plugin-sitemap: ^6.5.0 => 6.5.0project directory and paste the output here.
```

**Comment by LekoArts** [comment]
Hi!

If you want to change the footer, you can shadow the file: https://github.com/LekoArts/gatsby-themes/blob/main/themes/gatsby-theme-minimal-blog/src/components/footer.tsx

https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/

**Comment by halkeye** [comment]
I mean i can absolutely do it, but the default behavior is actually bad for people, Its probably better to not have a copyright statement rather than have an incorrect one.
