### ISSUE TITLE
[gatsby-theme-jodie]: The image on the Art has oversized

### ISSUE THREAD

**Issue by torn4dom4n** [LekoArts/gatsby-themes#1153]
## Description

The image on the Art has oversized.

### Steps to reproduce

- Open this link: https://jodie.lekoarts.de/art
- Open DevTool and Toggle the device emulation to mobile
- You can see the image doesn't fit with the page width. I captured pictures with Microsoft Edge (`Ctrl + Shift + S`).

Mobile: ![image](https://user-images.githubusercontent.com/27698189/229838481-cefccd92-b67d-4789-a3d2-318349d87dd1.png)

Desktop: 
![image](https://user-images.githubusercontent.com/27698189/229839216-54d344d2-0ef1-4791-ab7d-b9b96a348589.png)

## Expected result

When I opened https://jodie.lekoarts.de/color-in-all-its-glory, it looked good to me

![image](https://user-images.githubusercontent.com/27698189/232102141-b2145b85-e36a-49d9-b168-794532b6522d.png)

**Comment by LekoArts** [comment]
Hi! Please follow the issue template and provide more information about your problem. Where did you see this happen? What are the exact versions you‘re using?
