### ISSUE TITLE
[https://themes.lekoarts.de/]: webGL error on official page!

### ISSUE THREAD

**Issue by ymw0407** [LekoArts/gatsby-themes#1257]
## Description
If you enter in an environment where webGL is not active, an error occurs in the console window as follows.
Therefore, it would be nice to have a notification or a page that allows you to access the blog even if webGL is not enabled, or to activate webGL.

![image](https://github.com/LekoArts/gatsby-themes/assets/77202633/c5a97189-d303-4945-8878-44ca15a1e626)

Unlike Chrome, Firefox works well! I've currently tried to enable webGL 2.0 on Chrome, but it doesn't seem to go well!
![image](https://github.com/LekoArts/gatsby-themes/assets/77202633/200227c1-e7ff-4eea-aa71-95b942eccadd)

### Steps to reproduce
Occurs in the default state of Chrome browser where webGL 2.0 is not enabled.

### Expected result
Just letting you know that webGL is not active and you can't use it, like [jstris](https://jstris.jezevec10.com/), will help you a lot in terms of accessibility.
![image](https://github.com/LekoArts/gatsby-themes/assets/77202633/fc2fa74e-ac32-41c6-8726-41ea6cf0cbb5)

### Actual result

What happened.

**Comment by LekoArts** [comment]
Thanks for the issue but I can't reproduce :)
