### ISSUE TITLE
Emma: Header Navigation Spacing. 

### ISSUE THREAD

**Issue by kodenum** [LekoArts/gatsby-themes#129]
## Description

In the theme Emma when adding new pages there is no space between the titles. 

Describe the issue that you're seeing.

### Steps to reproduce

Add new page directory in the pages and add index.mdx

### Expected result

There should be some space between the navigation items.
### Actual result

Instead, there is no space 

### Environment

  System:
    OS: Windows 10
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4
  Browsers:
    Chrome

**Comment by LekoArts** [comment]
Thanks for the bug report!

```
Successfully published:
 - @lekoarts/gatsby-theme-emma@1.0.13
```
