### ISSUE TITLE
Minimal blog Live preview crashes on "Fantastic Beasts" page

### ISSUE THREAD

**Issue by freddydumont** [LekoArts/gatsby-themes#168]
## Description

Crash and white page on https://minimal-blog.lekoarts.de/fantastic-beasts-and-where-to-find-them. Here's the log:

<img width="565" alt="Capture d’écran, le 2019-11-26 à 11 33 50" src="https://user-images.githubusercontent.com/15388588/69653262-ea1de300-1040-11ea-89f3-ab4562471e05.png">

### Steps to reproduce

Go to this url: https://minimal-blog.lekoarts.de/fantastic-beasts-and-where-to-find-them. It crashes instantly for me on Brave and Firefox.

**Comment by freddydumont** [comment]
It also crashes on this page: https://minimal-blog.lekoarts.de/harry-potter-and-the-half-blood-prince

**Comment by LekoArts** [comment]
Thanks for the issue! I reverted the lazy loading part which caused this and will re-add it with a test checking it and having it actually work. Weirdly enough my testing didn't show this.

```
Successfully published:
 - @lekoarts/gatsby-theme-minimal-blog@1.1.1
```

v1.1.1 has the old code and if you visit the preview again it should work for you :)
