### ISSUE TITLE
Using MDX with shadowing in minimal-blog-theme

### ISSUE THREAD

**Issue by chkrishnatej** [LekoArts/gatsby-themes#174]
## Summary
Shadowing can be used only when the [file extension is not mentioned in the imports](https://www.gatsbyjs.org/docs/themes/shadowing/#file-extensions-can-be-overridden) for `homepage.tsx`. 

## Relevant information
When the `homepage.tsx` is being shadowed, the MDX content in the `hero.mdx` and `bottom.mdx` cannot be imported into the `homepage.tsx` successfully. 
I have a custom version of both `hero.mdx` and `bottom.mdx`. The shadow file `homepage.tsx` is not rendering the shadow file instead rendering the one in `node_modules`. I tried installing `gatsby-plugin-mdx`, still nothing was being overwritten.

I actually want to decrease the `margin-bottom` in the template. Is there any workaround for this?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thanks for the issue!
Since I wrote that part of the doc I know it 😆 
Maybe my editor edited it.

```
Successfully published:
 - @lekoarts/gatsby-theme-minimal-blog@1.1.3
```

Try the new release of the theme.

**Comment by chkrishnatej** [comment]
Thanks a lot for the update.
