### ISSUE TITLE
Header in minimal-blog-theme

### ISSUE THREAD

**Issue by chkrishnatej** [LekoArts/gatsby-themes#180]
## Summary
A floating/fixed header and a burger menu for better organization of navigation menu

#### Brief explanation of the feature.
- Floating/fixed header
    - A floating or a fixed header could give an easy access to the navigation menu which could be a nice addition

- Burger Menu
    - The two step navigation bar looks a little bit out of place(I ❤️  the theme and I am gonna use it for my blog). I thought it could be a nice addition to have the navigation menu items and site title in a single row.
    - And in the mobile view it could be stacked up like a burger menu
    - The theme toggle could be available in the header at all times in the header or put in the burger menu

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?
> The starter theme would look more polished and be a nice thing to use. 😄

**Comment by LekoArts** [comment]
Hi, thanks for the issue and happy to hear that you enjoy the theme!

The two step navigation is on purpose and generally speaking I don't want to add things to my themes that are not crucial to everyone. This feels more like personal preference and you're able to make these changes by shadowing the header :)

Thanks for understanding!
