### ISSUE TITLE
Would like to know how npm install is useful for a theme?

### ISSUE THREAD

**Issue by akanshgulati** [LekoArts/gatsby-themes#183]
@LekoArts  Hi, I saw that for installation you have mentioned `npm install @lekoarts/gatsby-theme-emma`. But could not understand how we can get the code as a template using it.

**Comment by tunnckoCore** [comment]
Use it as any other `gatsby-plugin-`: put it on the `gatsby-config.js` and read about the [Theme Shadowing](https://www.gatsbyjs.org/docs/themes/shadowing/), it's pretty easy and intuitive. :wine_glass:

**Comment by LekoArts** [comment]
The theme bundles most of it (the "template"), you'll only need to add content to it or shadow specific files to change things up. As tunnckoCore said it's like a Gatsby plugin.

You can also see an example usage in the linked starter:
https://github.com/LekoArts/gatsby-starter-portfolio-emma

Hope that helps!

**Comment by akanshgulati** [comment]
@LekoArts I downloaded the starter pack a year back, customised it for my use-case. Felt, it could be useful for others, removed all content part, added some examples and felt, yes that's all is required. Well, its whole lot different to create a theme than what I thought. Thanks a lot for sharing the info.
