### ISSUE TITLE
How do I change the background image/images to the cara starter project? 

### ISSUE THREAD

**Issue by Tc2r1** [LekoArts/gatsby-themes#194]
## Relevant information

I would like to make the moving shapes into a custom image that behaves the same as the current shapes. I would like to change the background image into something more custom as well. 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

> I would like to know how to go about changing either the moving background shape images to something else

You could shadow the `svg.tsx` file:
https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-cara/src/components/svg.tsx

If you keep the names the same you only have to change that. If you want to place them differently and/or name in another way, you'll need to also shadow the respective pages:
https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-cara/src/components

> the background image used in the Cara project to something custom

The background images are all a combination of "background color" + "shapes". The former can be changed in Theme UI, the latter with shadowing the pages like hero, projects, about, contact (see previous link).

Hope that helps!

**Comment by copocaneta** [comment]
> You could shadow the svg.tsx file

sorry for the dumb question but I am trying to shadow the svg.tsx file but I cant figure out how. I created a "components" directory inside my src dir and copied the svg.tsx file into there and changed the shapes but the svg.tsx file is not being shadowed, could you please help me and point out exactly how to shadow it?

I also noticed there is a relative path for "../styles/utils" which perhaps also should be changed?

Thanks for the superb work!
