### ISSUE TITLE
Minimal Blog: Base path is missed in the tags component

### ISSUE THREAD

**Issue by Deerhound579** [LekoArts/gatsby-themes#203]
### Description
I changed the base path to `/blog`, so the link for each tag should be`/blog/tags/{tagname}`. Instead, I got `/tags/{tagname}` which gives 404.

### Fix

https://github.com/LekoArts/gatsby-themes/blob/f1c9ffac108c5874d40bdb246a332437eabf918c/themes/gatsby-theme-minimal-blog/src/components/tags.tsx#L32

The link here should be 
```javascript
const { basePath, tagsPath } = useSiteMetadata()
...
to={`/${basePath}/${tagsPath}/${kebabCase(listItem.fieldValue)}`.replace(/\/\/+/g, `/`)}
```

**Comment by LekoArts** [comment]
Thanks for the issue. Fixed in:

```
Successfully published:
 - @lekoarts/gatsby-theme-minimal-blog@1.1.6
```
