### ISSUE TITLE
I'd like to know if this is available in JavaScript

### ISSUE THREAD

**Issue by spences10** [LekoArts/gatsby-themes#204]
I love the code highlight example @LekoArts!

Thanks for sharing this, Id like to know if there are any examples of this in JavaScript I could see to help me understand better how it's done.

Also what does the Regex (`const RE = /{([\d,-]+)}/`) do? 

https://github.com/LekoArts/gatsby-themes/blob/f1c9ffac108c5874d40bdb246a332437eabf918c/themes/gatsby-theme-minimal-blog/src/components/code.tsx#L56-L72

**Comment by kbiedrzycki** [comment]
Hi @spences10. Can you be more specific what are you looking for in JS? The code shared above is a TypeScript code, but simply dropping types will give you a code in JS actually.

And about that regex pattern - https://regex101.com/r/ZEvfAk/1 - this one matches the part with defined lines that should be highlighted when code is inserted in post body.

**Comment by LekoArts** [comment]
Kamil pretty much already explained it :) There is not much TS "magic" to this so it's basically JS. The regex catches the required syntax for highlighting, the rest is extracting the data into a suitable format. `RE.exec(meta)![1]` is the `Group 1` match for example.
