### ISSUE TITLE
How do I change SiteDescription and siteImage in gatsby-config.js?

### ISSUE THREAD

**Issue by jvbylen** [LekoArts/gatsby-themes#205]
As per title. My website keeps defaulting to the generic lekoarts banner and description.

**Comment by LekoArts** [comment]
You overwrite the values in your `gatsby-config.js` file:

```js
module.exports = {
  siteMetadata: {
    siteDescription: `Your description.`,
    siteImage: `/your-image-path.jpg`,
  },
}
```

**Comment by LekoArts** [comment]
Thank you for opening this!

I'm marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. Thanks for using my themes!

**Comment by jidicula** [comment]
I'm having the same issue. I first tried adding my own `banner.jpg` image in `static/`, but my site continued to default to the LekoArt banner with my own site's description:

![image](https://user-images.githubusercontent.com/12765385/89430716-082dfe00-d70d-11ea-9dbd-16b1b2e62361.png)

Then, I tried changing the value in `gatsby-config.js` to point to a PNG version of my banner instead: `siteImage: "/banner.png"`, which is also in the `static/` dir. This leads to no banner being shown in link previews:

![image](https://user-images.githubusercontent.com/12765385/89430933-47f4e580-d70d-11ea-98ca-620855ecc790.png)

I'm not quite sure what I'm doing wrong here. I cloned my repo from a [friend's site repo](https://github.com/krubenok/nerd-ramblings), and he had just added a new `banner.jpg` in the same location without changing the value of `siteImage` (which I tried first, described above), and his site's link previews show his banner as expected:

![image](https://user-images.githubusercontent.com/12765385/89431195-986c4300-d70d-11ea-9614-98d43abb5632.png)

Does anyone have a fix for this?

**Comment by LekoArts** [comment]
This is probably an intermittent issue with the scraping for the preview (cached response). Changing the file should be enough.

**Comment by jidicula** [comment]
> This is probably an intermittent issue with the scraping for the preview (cached response). Changing the file should be enough.

Good to know! And just to clarify, the preview image is format-agnostic, right? It should be ok to use a PNG instead of a JPG?

**Comment by LekoArts** [comment]
As long as you overwrite the `siteImage` property, yeah.

**Comment by mohammedpatla** [comment]
I tried clearing cache and building the repo again (on Netlify), but does not seem to work for me I still get the default banner.
Although I already replaced it with a new banner.

```
siteMetadata: {
    // Used for the title template on pages other than the index site
    siteTitle: `Secure Secrets`,
    // Default title of the page
    siteTitleAlt: `Securing the secentralized web`,
    // Can be used for e.g. JSONLD
    siteHeadline: `Secure your Secrets`,
    // Will be used to generate absolute URLs for og:image etc.
    siteUrl: `https://securesecrets.network`,
    // Used for SEO
    siteDescription: `Securing the decentralized web using Secret Network`,
    // Will be set on the <html /> tag
    siteLanguage: `en`,
    // Used for og:image and must be placed inside the `static` folder
    siteImage: `/banner.jpg`,
    // Twitter Handle
    author: `@mohammedpatla`,
    // Navigation links
  }
```

![image](https://user-images.githubusercontent.com/16710191/90469878-ffafcd00-e0e7-11ea-9bc0-2dd56471c895.png)

Any suggestions @LekoArts 

Were you able to get yours to work @jidicula ?

**Comment by jidicula** [comment]
> I tried clearing cache and building the repo again (on Netlify), but does not seem to work for me I still get the default banner.
> 
> Although I already replaced it with a new banner.
> 
> 
> 
> ```
> 
> siteMetadata: {
> 
>     // Used for the title template on pages other than the index site
> 
>     siteTitle: `Secure Secrets`,
> 
>     // Default title of the page
> 
>     siteTitleAlt: `Securing the secentralized web`,
> 
>     // Can be used for e.g. JSONLD
> 
>     siteHeadline: `Secure your Secrets`,
> 
>     // Will be used to generate absolute URLs for og:image etc.
> 
>     siteUrl: `https://securesecrets.network`,
> 
>     // Used for SEO
> 
>     siteDescription: `Securing the decentralized web using Secret Network`,
> 
>     // Will be set on the <html /> tag
> 
>     siteLanguage: `en`,
> 
>     // Used for og:image and must be placed inside the `static` folder
> 
>     siteImage: `/banner.jpg`,
> 
>     // Twitter Handle
> 
>     author: `@mohammedpatla`,
> 
>     // Navigation links
> 
>   }
> 
> ```
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/16710191/90469878-ffafcd00-e0e7-11ea-9bc0-2dd56471c895.png)
> 
> 
> 
> Any suggestions @LekoArts 
> 
> 
> 
> Were you able to get yours to work @jidicula ?

Not exactly, the link preview still doesn't show my banner image, but it's not displaying the template banner anymore.

**Comment by mohammedpatla** [comment]
@jidicula I think I fixed the issue, by creating a copy of the banner.jpg in the src/../sections/ folder

**Comment by jidicula** [comment]
@mohammedpatla where is the `src/.../sections/` folder? I'm using the minimal blog theme, my project repo can be seen [here](https://github.com/jidicula/forcepush).

Good to hear that it works fine on Discord, so that means that LinkedIn and Telegram might be slower to refresh their caches for unravelling link previews?

**Comment by mohammedpatla** [comment]
Um not too sure where this would be for you @jidicula 
But I think you can place it in /components or /src and try.

**Comment by jidicula** [comment]
Update: seems fine for me now, with the banner card being generated as expected.

**Comment by yeliudev** [comment]
> Update: seems fine for me now, with the banner card being generated as expected.

Hi @jidicula! Thank you for pointing out the issue. I meet the exact same issue as yours. May I ask that how did you solve the problem? Are you still using placing the `banner.jpg` at `static/`?

**Comment by jidicula** [comment]
> > Update: seems fine for me now, with the banner card being generated as expected.
> 
> 
> 
> Hi @jidicula! Thank you for pointing out the issue. I meet the exact same issue as yours. May I ask that how you solved the problem? Are you still placing the `banner.jpg` at `static/`?

I am, and it fixed itself somehow - I think it's some kind of black-box caching on each platform that does card previews. You can see my site repo [here](https://github.com/jidicula/forcepush).

**Comment by yeliudev** [comment]
@jidicula Thanks for your kind reply! I'll check the cache.
