### ISSUE TITLE
Minimal Blog: Language tabs for code blocks are not fixed

### ISSUE THREAD

**Issue by Deerhound579** [LekoArts/gatsby-themes#207]
## Description

The language tab is moving with the whole container. This happens during my development, and I found the same problem on the demo site.
![issue](https://user-images.githubusercontent.com/43892874/71745531-5fe34e80-2e38-11ea-9001-2077485bde7b.gif)

### Steps to reproduce

Try scrolling code block on the [demo site](https://minimal-blog.lekoarts.de/fantastic-beasts-and-where-to-find-them)

### Temporary fix
I made some changes under `.prism-code` and `.gatsby-highlight` to position the element and make it sticky. Is there a better way to do it?
```javascript
".prism-code" :{
    ... 
    mt: `-1rem`
}

".gatsby-highlight":{
    ...
    padding: `0.4rem 0.5rem`,
    position: `sticky`,
    left: `1rem`,
}
```
![Kapture 2020-01-03 at 15 00 04](https://user-images.githubusercontent.com/43892874/71745981-c7e66480-2e39-11ea-82b9-dffee48f1b08.gif)

**Comment by LekoArts** [comment]
Hi, thanks for the issue! It's working as intended but feel free to change the CSS on your site if you prefer another behavior.

**Comment by jhcccc** [comment]
> Hi, thanks for the issue! It's working as intended but feel free to change the CSS on your site if you prefer another behavior.

I think it would be better if the language sticker can stick at the corner. It would be more intuitive and makes more sense.
