### ISSUE TITLE
MDX on theme

### ISSUE THREAD

**Issue by antonybudianto** [LekoArts/gatsby-themes#208]
## Description

First of all, thank you for the theme, it's very cool!

I got mdx duplicate error, so I thought the issue is:
https://github.com/LekoArts/gatsby-themes/blob/e798a7d962a2259ded90356185c5602af40e8ae8/themes/gatsby-theme-cara/gatsby-config.js#L21

I saw the other themes have mdx validation:
https://github.com/LekoArts/gatsby-themes/blob/9940a5756834e36141ed99c95db1b0e6d83357d4/themes/gatsby-theme-graphql-playground/gatsby-config.js#L29

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Fixed in:

```
Successfully published:
 - @lekoarts/gatsby-theme-cara@1.0.15
```
