### ISSUE TITLE
Minimal Blog: Weird cursor position in live code editor

### ISSUE THREAD

**Issue by Deerhound579** [LekoArts/gatsby-themes#211]
Hi, I found the cursor position is not aligned with the line. The [official demo](https://react-live.netlify.com/) of `react-live` works as expected. Is there a way to fix this? Thank you!
![Kapture 2020-01-04 at 16 15 40](https://user-images.githubusercontent.com/43892874/71771700-ab1b6100-2f0d-11ea-9407-52d8ef68028b.gif)
The recording is from the [minimal blog demo site](https://minimal-blog.lekoarts.de/fantastic-beasts-and-where-to-find-them).

**Comment by LekoArts** [comment]
Should be fixed in `@lekoarts/gatsby-theme-minimal-blog@1.1.8`. Thanks for the issue!
