### ISSUE TITLE
Cara Theme - can't customize and add email box

### ISSUE THREAD

**Issue by Hewlbern** [LekoArts/gatsby-themes#216]
Hi there,
I love the Cara Theme but have been unable to work out how to customize it.

I basically want to add a subscribe button and edit out a few parts of the starter.

I'm used to react and next,so unsure how to edit this theme as there's no files available anywhere?

This is the github https://github.com/Hewlbern/gatsby-starter-Rhea

Cheers!

**Comment by LekoArts** [comment]
Thank you for opening this!

Have a look at the README of the theme to learn how to customize the MDX files:
https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-cara

If you want to edit more parts of this Gatsby theme you'll need to shadow these files:
https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-cara/src/components

Explanation of shadowing: https://www.gatsbyjs.org/docs/themes/shadowing/
Tutorials for Gatsby themes: https://github.com/LekoArts/gatsby-themes#-learning-gatsby-themes

I'm marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. Thanks for using my themes!
