### ISSUE TITLE
Is there any way not to use automatic mapping slug for post?

### ISSUE THREAD

**Issue by JuneBuug** [LekoArts/gatsby-themes#217]
## Summary

Gatsby supports explicitly configure post path, but minimal blog theme seems not to support it.
Can I configure post path with adding 'path' to frontmatter?

## Relevant information

https://www.gatsbyjs.org/docs/mdx/writing-pages/#using-frontmatter-in-mdx
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thanks for the issue! You should be able to define a `slug` in the frontmatter now in:

```
 - @lekoarts/gatsby-theme-minimal-blog-core@1.1.0
 - @lekoarts/gatsby-theme-minimal-blog@1.2.0
```

Like: `slug: "/my-slug"`

**Comment by JuneBuug** [comment]
@LekoArts you are the fastest developer & project maintainer I've ever seen! thx for the kind response.
