### ISSUE TITLE
How do I add additional Gatsby Remark Plugin for mdx

### ISSUE THREAD

**Issue by sabbiu** [LekoArts/gatsby-themes#218]
I want to add this additional plugin to mdx ([remark-math-katex](https://github.com/Rokt33r/remark-math)). I am using `gatsby-theme-minimal-blog` as a theme.

Seems that you have it in `@lekoarts/gatsby-theme-minimal-blog-core/gatsby-config.js` as,
```javascript
  mdx && {
        resolve: `gatsby-plugin-mdx`,
        options: {
          gatsbyRemarkPlugins: [
            {
              resolve: `gatsby-remark-images`,
              options: {
                maxWidth: 960,
                quality: 90,
                linkImagesToOriginal: false,
              },
            },
          ],
          plugins: [
            {
              resolve: `gatsby-remark-images`,
              options: {
                maxWidth: 960,
                quality: 90,
                linkImagesToOriginal: false,
              },
            },
          ],
        },
      },
```
How do I extend that plugin list from my project?

**Comment by LekoArts** [comment]
Hi, thanks for opening the issue! You'll need to set the option `mdx` to false and then you can define this yourself in your `gatsby-config.js` file. Keep in mind that you'll initially need to copy what I currently have and then add your other things.
