### ISSUE TITLE
Heading preview text customizable

### ISSUE THREAD

**Issue by CanRau** [LekoArts/gatsby-themes#219]
Hey Lennart, thanks for this cool theme 🙏 

## Summary

What do you think about the option to customize the `Heading` text preview?

### Basic example

1. and easiest option would be to just allow customization via string prop like
```js
<Heading
  styles={{..}}
  theme={theme}
  previewText="The quick brown fox.."
/>
```

2. or allow an object
```js
const previewTexts = {
  h1: "The quick brown fox jumps over the lazy dog",
  h2: "..",
}
<Heading
  styles={{..}}
  theme={theme}
  previewText={previewTexts)
/>
```
or maybe even both

### Motivation
I think, personally, that it looks much more appealing and closer to real life. 

👋 Liebe Grüße aus'm Dschungel 🇵🇪 
Bin übrigens ursprünglich aus Berlin 🇩🇪
😃

**Comment by LekoArts** [comment]
Option 1 seems like a good addition! Thanks for the issue :)
Don't know when I'll have time to add this so feel free to send in a PR 🎉

**Comment by LekoArts** [comment]
```
Successfully published:
 - @lekoarts/gatsby-theme-specimens@2.1.0
 - @lekoarts/gatsby-theme-styleguide@1.0.7
```
