### ISSUE TITLE
Shadow/Alter Theme Colors (cara theme)

### ISSUE THREAD

**Issue by richdacuban** [LekoArts/gatsby-themes#233]
## Summary
>Using Cara theme, I can't seem to shadow  `dir/node_modules/@lekoarts/gatsby-theme-cara/src/gatsby-plugin-theme-ui/index.js` and alter colors
## Relevant information
>I've shadowed what I believe is the theme-ui definition in node_modules like this:  `dir/src/@lekoarts/gatsby-theme-cara/gatsby-plugin-theme-ui/index.js` but no matter what colors I try to change nothing changes BUT if I edit the same file but in node_modules I can modify everything successfully...  

>To be clear, I'm referring to changing divider color (to orange, let's say) in both these files in order to try to see changes:
` colors: {
    ...tailwind.colors,
    primary: tailwind.colors.orange[4],
    secondary: tailwind.colors.indigo[6],
    text: tailwind.colors.gray[3],
    heading: tailwind.colors.white,
    background: `#141821`,
    divider: tailwind.colors.gray[8],
    textMuted: tailwind.colors.gray[5],
    //...
   }`
>The changes only appear when I edit  `dir/node_modules/@lekoarts/gatsby-theme-cara/src/gatsby-plugin-theme-ui/index.js`. EDIT: I want to add that I can successfully shadow and modify all the other components and files in the site, it's just this one that doesn't seem to work.

>Am I shadowing the file incorrectly? Thanks in advance and thanks for you awesome work, I'm learning a lot from it!

### Environment (if relevant)

>  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 11.13.0 - C:\Program Files\nodejs\node.EXE    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD    
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.13.72 => 2.19.1
    gatsby-cli: ^2.8.27 => 2.8.27
    gatsby-plugin-google-analytics: ^2.1.8 => 2.1.33    gatsby-plugin-manifest: ^2.2.6 => 2.2.37        
    gatsby-plugin-netlify: ^2.1.6 => 2.1.31
    gatsby-plugin-offline: ^2.2.7 => 2.2.10

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

If you want to shadow the Theme UI config, you'll need to create a file at `src/gatsby-plugin-theme-ui/index.js` like explained here: https://www.gatsbyjs.org/docs/theme-ui/#using-theme-ui-in-a-gatsby-theme

You'll want to import the `baseTheme` from `@lekoarts/gatsby-theme-cara/src/gatsby-plugin-theme-ui` then.

Hope that helps!
