### ISSUE TITLE
[Emma] First Load Broken CSS

### ISSUE THREAD

**Issue by Skillz4Killz** [LekoArts/gatsby-themes#236]
## Description

A few users have reported that when they first opened the website, it looked entirely broken and really messed up but on refresh it was immediately solved and it looked great. This didn't make sense to me and I wasn't able to replicate it myself. Then a user recently came along with some experience of web dev who showed me how to replicate it. If I open my website https://gamer.netlify.com in Private mode it will treat me as a first time user and then I am able to see the CSS is completely broken.

Repo: https://github.com/Skillz4Killz/gamer-wiki

### Steps to reproduce

Either go to the website for the first time. OR turn on privacy mode in your browser and go to the website.

### Expected result

What should happen?
![image](https://user-images.githubusercontent.com/23035000/73038076-1f676700-3e1f-11ea-96ea-ac72934dc90a.png)

### Actual result

![image](https://user-images.githubusercontent.com/23035000/73038064-14acd200-3e1f-11ea-9e39-9dd18735a848.png)

### Environment

```js

  System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 12.1
  npmPackages:
    gatsby: ^2.19.3 => 2.19.3 
    gatsby-plugin-manifest: ^2.2.38 => 2.2.38 
    gatsby-plugin-mdx: ^1.0.67 => 1.0.67 
    gatsby-plugin-netlify: ^2.1.31 => 2.1.31 
    gatsby-plugin-offline: ^3.0.32 => 3.0.32 
    gatsby-plugin-sitemap: ^2.2.26 => 2.2.26 
  npmGlobalPackages:
    gatsby-cli: 2.8.27
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Unfortunately I'm unable to replicate this issue with my starter so it has something to do with your modifications. I'd recommend creating a new branch in your project, removing all changes and gradually adding it again. Push the changes in between and you can see a preview on Netlify (or test it locally with `gatsby build & gatsby serve`). Maybe your Discord widget is messing things up.

Hope you resolve your issue!
