### ISSUE TITLE
[Emma] HomePage Mobile Hover Effect

### ISSUE THREAD

**Issue by Skillz4Killz** [LekoArts/gatsby-themes#238]
## Summary

The css effects that are done on the hover effect on the homepage do not translate well to the mobiles. Hover effect is difficult to replicate and therefore in the emma theme the entire page just looks like a gallery of images as opposed to posts/articles/guides whatever. Until a user clicks it they realize o this is something that can be clicked on. It's not intuitive and would look much nicer if a different style of effect was used on mobile devices. 

Perhaps just a slight animation every few seconds forcing the hover vs non-hover view.

### Basic example

Sorry my css skills are lacking which is why i decided to use a theme. My best guess would be something along the lines of.

I would recommend on mobile view to possibly consider using a different style like

```js
<div>
  <Image />
  <div>
    <Title />
    <Subdescription />
  </div>
</div>
```

### Motivation

The mobile user's hover effect is really bad. It is not user-intuitive and upon research into this problem, I discovered hover effect on mobile can cause a need to double-tap the image to open it up as well.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Implementing hover effects for mobile users is a really big topic and people try to solve it in different ways for years now. I've seen a lot of similar websites to that theme solve it in the same way, meaning there is no distinctive hover style for mobile users. So I won't change anything.

However, you can of course change the theme to your liking by applying CSS. I wouldn't recommend the on-off animation you suggested but maybe showing the overlay with 50% and the text 100%?

Hope that helps. Thanks for using the theme!
