### ISSUE TITLE
Use Theme UI Container component

### ISSUE THREAD

**Issue by kripod** [LekoArts/gatsby-themes#263]
## Summary

In order to constrain the width of the resulting page, the customizable [`Container` component](https://theme-ui.com/components/container) of Theme UI should be used. An option could be provided to opt out from using a `Container`, e.g. for `gatsby-theme-specimens`.

### Motivation

Improve out-of-the-box user experience by adding a reasonable amount of padding for generated pages.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Not too sure to which theme you're referring to. `gatsby-theme-specimens` is a collection of React components so there is no need for a layout component. All other themes allow to shadow the component (often "Layout") that is wrapping the content and/or setting the max-width of the content.

Thus I'm closing the issue. Feel free to give more information if needed.

**Comment by kripod** [comment]
I was referring to `gatsby-theme-styleguide`, sorry for the ambiguity.
