### ISSUE TITLE
[theme-styleguide] Add support for color modes

### ISSUE THREAD

**Issue by kripod** [LekoArts/gatsby-themes#266]
## Summary

Similarly to the docs of Theme UI, a [color mode toggle](https://theme-ui.com/guides/color-mode-toggles/) should be present to show the contrasts e.g. between dark mode colors.

### Motivation

Different color modes should be visually testable on their own.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

The styleguide theme is intentionally really bare bones as it should be integrated into an existing site or built into a new site. If you want a color mode toggle, please add it to your site yourself. Thanks!
