### ISSUE TITLE
Cant create new blog posts inside gatsby-starter-minimal-blog

### ISSUE THREAD

**Issue by mojovski** [LekoArts/gatsby-themes#267]
Hey there,
in my case the creating of new blog posts does not work.
I created a new index.mdx file inside posts/test-article
```
myblog/
  └───content/
      └───posts/
          └───test-article/
              └─  index.mdx
```

but the new article is not displayed.
The content of index.mdx:
```
---
title: "Test Article"
date: 2020-02-06
---

Hello everyone. good news!
```

The output from `gatsby develop` looks fine to me.

```
➜  blog git:(master) ✗ gatsby develop
success open and validate gatsby-configs - 0.095s
success load plugins - 1.269s
warn The Google Analytics plugin requires a tracking ID. Did you mean to add it?
success onPreInit - 0.027s
success initialize cache - 0.011s
success copy gatsby files - 0.057s
success onPreBootstrap - 0.020s
success createSchemaCustomization - 0.015s
success source and transform nodes - 0.241s
success building schema - 0.833s
success createPages - 0.119s
success createPagesStatefully - 0.096s
success onPreExtractQueries - 0.009s
success update schema - 0.074s
success extract queries from components - 0.686s
success write out requires - 0.099s
success write out redirect data - 0.010s
success Build manifest and related icons - 0.005s
success onPostBootstrap - 0.064s
⠀
info bootstrap finished - 7.852 s
⠀
success run queries - 0.080s - 2/2 24.88/s
⠀
You can now view minimal-blog in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
```

Any ideas where I can look next?

**Comment by mojovski** [comment]
Update: When I have a look on the GraphiQl interface, the new blog post is found:
```
query MyQuery {
  allPost {
    edges {
      node {
        id
        title
      }
    }
  }
}
```

returns
```
{
  "data": {
    "allPost": {
      "edges": [
        {
          "node": {
            "id": "29d59fbf-9f1e-5f81-b330-81769bbcded9",
            "title": "Title 22"
          }
        },
        {
          "node": {
            "id": "8fecf521-3e24-5d5c-91bf-a2c9793f9126",
            "title": "Titel 1"
          }
        },
        {
          "node": {
            "id": "b5961cd5-cdee-58d6-a8e4-ed6ae89759a3",
            "title": "Harry Potter and the Half-Blood Prince"
          }
        },
        {
          "node": {
            "id": "120c8979-fc6d-5d86-bf9c-5493d726179d",
            "title": "Introduction to \"Defence against the Dark Arts\""
          }
        },
        {
          "node": {
            "id": "b0974a7c-2223-50fe-a520-31084074e63c",
            "title": "Test Article"
          }
        }
      ]
    }
  }
}
```

So the "test Article" is found.

**Comment by mojovski** [comment]
Gatsby info:
```
  System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Xeon(R) CPU           W3565  @ 3.20GHz
    Shell: 5.1.1 - /usr/bin/zsh
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
  Languages:
    Python: 3.7.2 - /home/eugen/.pyenv/shims/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 72.0.1
  npmPackages:
    gatsby: ^2.13.3 => 2.19.12
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.35
    gatsby-plugin-manifest: ^2.2.3 => 2.2.41
    gatsby-plugin-netlify: ^2.1.3 => 2.1.32
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sitemap: ^2.2.19 => 2.2.27
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8
  npmGlobalPackages:
    gatsby-cli: 2.8.29

```

**Comment by mojovski** [comment]
It looks like that the GraphQL query applies the "limit 3" first and then sorts by date.
I dont know yet how to fix it, but setting limit: 13 in
https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog-core/src/templates/homepage-query.tsx#L8

shows also the latest posts.

**Comment by mojovski** [comment]
another update: the sorting of the posts is applied on the FORMATTED date.

Setting
```
query {
    allPost(sort: { fields: date, order: DESC }, limit: 3) {
      nodes {
        slug
        title
        date
        tags {
          name
          slug
        }
      }
    }
  }
```
(removing the `date(formatString: "DD.MM.YYYY")`line, also resolves the issue. However, the date string in the html looks then like this: `2020-02-08T00:00:00.000Z`

**Comment by kylebarron** [comment]
For me, adding a post **does show up on the index page**:
![image](https://user-images.githubusercontent.com/15164633/73872894-8f61ee00-481e-11ea-9098-34d619c4b273.png)

And the page exists:
![image](https://user-images.githubusercontent.com/15164633/73873095-f384b200-481e-11ea-8293-6af5d3ebbfb2.png)


But it **_doesn't show up on `/blog`_**:
![image](https://user-images.githubusercontent.com/15164633/73872930-a0126400-481e-11ea-96d1-ffb4374ab87b.png)

Here's the example file at `content/posts/test-post/index.mdx` (I had to restart `gatsby develop` for it to see the page again):
```mdx
---
title: Test post
date: 2020-01-07
description: Defence Against the Dark Arts (abbreviated as DADA) is a subject taught at Hogwarts School of Witchcraft and Wizardry and Ilvermorny School of Witchcraft and Wizardry.
tags:
  - Tutorial
  - Dark Arts
# banner: ./defence-against-the-dark-arts.jpg
---

Hello world
```

**Comment by kylebarron** [comment]
After a bit more reloading of the gatsby dev server, I got the post to show up in `/blog`, but the post still doesn't show up on either `/tags/tutorial` or `/tags/dark-arts`, even though both tags are provided.

**Comment by kylebarron** [comment]
@mojovski I think I figured it out; the GraphQL queries are cached, so on the development server the queries aren't necessarily run again.

Try:
```bash
gatsby clean
gatsby develop
```
That works for me

**Comment by kylebarron** [comment]
@LekoArts it might be helpful to add a suggestion to run `gatsby clean` in the docs, [for example here](https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog#adding-a-new-blog-post), so that you don't get bothered by more people asking about it.

**Comment by mojovski** [comment]
Thanks @kylebarron ! `gatsby clean` resolves the issue
