### ISSUE TITLE
How to change date format?

### ISSUE THREAD

**Issue by gbailey4** [LekoArts/gatsby-themes#273]
## Summary
Currently, the date format in the starter https://www.gatsbyjs.org/starters/LekoArts/gatsby-starter-minimal-blog/ which relies on this theme uses a day first date format. This is not standard in the US and I'd like to be able to change to month first. Is this possible? I found the format files, but I'm unsure how to modify the output to the starter from the theme.

**Comment by gregjopa** [comment]
I just ran into the same issue. I'd like to override the dates in https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog-core/src/templates. 

Any recommendations on how to easily solve this?

**Comment by LekoArts** [comment]
Thanks for the issue! You can fix this yourself by shadowing the files with the queries inside. But that's cumbersome, so I'll release an update to those themes to expose a `formatString` option :)

**Comment by gregjopa** [comment]
> I'll release an update to those themes to expose a formatString option :)

That's an awesome idea! Thanks @LekoArts ❤️

**Comment by LekoArts** [comment]
```
Successfully published:
 - @lekoarts/gatsby-theme-emilia-core@1.2.0
 - @lekoarts/gatsby-theme-emilia@1.2.0
 - @lekoarts/gatsby-theme-emma-core@1.2.0
 - @lekoarts/gatsby-theme-emma@1.3.0
 - @lekoarts/gatsby-theme-minimal-blog-core@2.1.0
 - @lekoarts/gatsby-theme-minimal-blog@2.1.0
```

**Comment by cogito288** [comment]
Hello, I'm quite new to React and Gatsby.
I try to change the date format in blog post, so I shadowed _gatsby-theme-minimal-blog-core_. I changed utils/default-options.js.
`
const formatString = themeOptions.formatString || `YYYY.MM.DD`
`

However, it didn't change. How can I change the date format?

**Comment by LekoArts** [comment]
You'll need to change that via the options in the theme itself: https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog#theme-options

**Comment by cogito288** [comment]
Thank you @LekoArts . Just to clarify, shadowing gatsby-starter-minimal-blog-core does not affect gatsby-starter-minimal-blog theme, right?

**Comment by LekoArts** [comment]
Gatsby's shadowing mechanism only works for files inside the `src/` directory and as the default options are all configurable via the theme options itself I did place that file on purpose not in that directory.
If you change -core theme you'll also change the normal theme, yes, as it uses it.
