### ISSUE TITLE
Use description in BlogListItem component?

### ISSUE THREAD

**Issue by elihanover** [LekoArts/gatsby-themes#274]
Does anyone know how to use a blog post description in the listing?  When I use post.description I get an undefined object even after changing BlogListItemProps.

``` js
const BlogListItem = ({ post, showTags = true }: BlogListItemProps) => (
  <Box mb={4}>
    <p sx={{ color: `secondary`, mt: 1, a: { color: `secondary` }, fontSize: [20, 20, 1] }}>
      <time>{post.date}</time>
      {post.tags && showTags && (
        <React.Fragment>
          {` — `}
          <ItemTags tags={post.tags} />
        </React.Fragment>
      )}
    </p>
    <Styled.a as={Link} to={post.slug} sx={{ fontSize: [1, 2, 3], color: `text` }}>
      {post.title}
    </Styled.a>
    <p sx={{ color: `secondary`, mt: 1, a: { color: `secondary` }, fontSize: [1, 1, 2] }}>
      {post.description || 'TEST' }
    </p>

  </Box>
)
```

**Comment by LekoArts** [comment]
Thanks for the issue!

You would have needed to shadow the templates files from `gatsb-theme-minimal-blog-core` to alter the GraphQL query. However, this seems like a normal use case and one should have access to all default keys without shadowing. If the user wants to add additional fields they'll need to shadow.

You now can create a file at `src/@lekoarts/gatsby-theme-minimal-blog/components/blog-list-item.jsx` and access `timeToRead`, `excerpt` and `description` in addition to all fields that were already accessible:

```jsx
/** @jsx jsx */
import React from "react"
import { jsx, Styled } from "theme-ui"
import { Box } from "@theme-ui/components"
import { Link } from "gatsby"
import ItemTags from "@lekoarts/gatsby-theme-minimal-blog/src/components/item-tags"

const BlogListItem = ({ post, showTags = true }) => (
  <Box mb={4}>
    <Styled.a as={Link} to={post.slug} sx={{ fontSize: [1, 2, 3], color: `text` }}>
      {post.title}
    </Styled.a>
    <p sx={{ color: `secondary`, mt: 1, a: { color: `secondary` }, fontSize: [1, 1, 2] }}>
      <time>{post.date}</time>
      {post.tags && showTags && (
        <React.Fragment>
          {` — `}
          <ItemTags tags={post.tags} />
        </React.Fragment>
      )}
    </p>
    <p>{post.description}</p>
  </Box>
)

export default BlogListItem
```

It then looks like this:

![image](https://user-images.githubusercontent.com/16143594/75606671-77188280-5aef-11ea-9a8d-303722619a37.png)

Released in `@lekoarts/gatsby-theme-minimal-blog@2.2.0`

**Comment by allardbrain** [comment]
This helped me. Thank you!
