### ISSUE TITLE
How to change footer button and text

### ISSUE THREAD

**Issue by Sabir001** [LekoArts/gatsby-themes#280]
## Summary
I want to change the footer section button and texts in theme: gatsby-theme-cara

### Theme

gatsby-theme-cara

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Sabir001** [comment]
I have achieved this by adding `footer.tsx` file in `src/@lekoarts/gatsby-theme-cara/components` folder.

**Comment by stevenorechow** [comment]
Hi @Sabir001 Do you happen to have a repository or site I can reference to accomplish this?

**Comment by Sabir001** [comment]
Not a public one ...

I have made a gist for you ...
https://gist.github.com/Sabir001/7234232a0b90a6b3fdf9d24243f77eba

You just need to copy their `footer.tsx` and change parts you need to change ...

**Comment by ShreyaanVashishtha** [comment]
I tried but the site ended up breaking
