### ISSUE TITLE
[gatsby-theme-minimal-blog]: CSS for table

### ISSUE THREAD

**Issue by compliment** [LekoArts/gatsby-themes#281]
## Summary
Currently rendered table looks like worse than raw markdown as lines are omitted and just text is there. Also for some reason it doesn't respect bold or italic or monospace. 
### Basic example

This is how it currently renders a normal table.
![image](https://user-images.githubusercontent.com/22877365/75068155-8b082700-54e6-11ea-96ed-991a4b6f1800.png)

### Motivation

Well this is obvious.

**Comment by LekoArts** [comment]
If you want additional styles you'll need to extend the Theme UI config.
As a table is a common use case I went ahead and fixed it in: https://github.com/LekoArts/gatsby-themes/commit/6e3d750b01d0398fc2dd5b3d043754389a0f46ff

Update to `@lekoarts/gatsby-theme-minimal-blog@2.1.1` and you'll see default styles. If you want to change them, you'll need to extend the Theme UI config as I said :)
