### ISSUE TITLE
How to change number of thumbnails?

### ISSUE THREAD

**Issue by hitherepeople100** [LekoArts/gatsby-themes#292]
how would I change the number of thumbnails displayed on the screen in the emma theme.  I understand it's responsive, but would like to make fewer, larger thumbnails per row.  Thanks!

**Comment by hitherepeople100** [comment]
Hi there? I was looking around at the src files to see how to decrease the number of columns displayed (so each image thumbnail is larger).  I've looked through a lot of the pages, but don't know how to make each thumbnail take up a larger space in the EMMA THEME.  Any help would be appreciated.  Thanks!

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

The emma theme is using CSS Grid in its `projects` file:
https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-emma/src/components/projects.tsx#L63

Hence you'll need to shadow that file to overwrite the CSS.

So create a file at `src/@lekoarts/gatsby-theme-emma/components/projects.jsx`:

```jsx
/** @jsx jsx */
import { jsx } from "theme-ui"
import { useTrail } from "react-spring"
import Layout from "@lekoarts/gatsby-theme-emma/src/components/layout
import ProjectItem from "@lekoarts/gatsby-theme-emma/src/components/project-item"

const Projects = ({ projects }) => {
  const trail = useTrail(projects.length, {
    from: { height: `0%` },
    to: { height: `100%` },
  })

  return (
    <Layout
      sx={{
        display: `grid`,
        gridTemplateColumns: `repeat(auto-fit, minmax(280px, 1fr))`,
        width: `100%`,
      }}
    >
      {trail.map((style, index) => (
        <ProjectItem style={style} node={projects[index]} key={projects[index].slug} />
      ))}
    </Layout>
  )
}

export default Projects
```

And change `gridTemplateColumns` to your desired behavior.

Hope that helps!
