### ISSUE TITLE
Documentation on shadowing Theme UI could use some clarification

### ISSUE THREAD

**Issue by GabeEddyT** [LekoArts/gatsby-themes#300]
## Summary

I can successfully shadow other files, but I can't change the theme. I'm simply trying to get "dark" to be the default by setting `initialColorMode`. It would be nice to have an explicit full path, or a specific shadowing example showing where to put the file.

## Relevant information

> The Theme UI config can be configured by shadowing its files in src/gatsby-plugin-theme-ui/

![](https://i.imgur.com/hl9jl6G.png)

Regardless of where I put `gatsby-plugin-theme-ui/index.js`, nothing changes. The light theme is still the default.

### Theme

Emma (but I assume the other themes behave similarly)

**Comment by LekoArts** [comment]
Hi!

You'll need to create the file at `src/gatsby-plugin-theme-ui/index.js` as the documentation says ;)

You're confused by the name of the API: https://github.com/system-ui/theme-ui/issues/236#issuecomment-516067403

You'll need to switch dark to the root-level and light into the modes, e.g. like here: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-cara/src/gatsby-plugin-theme-ui/index.js#L5-L27

Hope that helps!
