### ISSUE TITLE
Zero-config ? 

### ISSUE THREAD

**Issue by yumyo** [LekoArts/gatsby-themes#306]
## Summary

The README states 

> — just install the theme and see your Theme UI config displayed in a beautiful manner.

However, it seems the theme expect a tailwind configuration instead?

### Theme

gatsby-starter-styleguide

### Question

How to use a theme-ui object like https://theme-ui.com/theme-spec/ ?

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You can use a Theme UI config just fine. In fact, you can only use such a config. The example also does that: https://github.com/LekoArts/gatsby-themes/blob/master/examples/styleguide/src/gatsby-plugin-theme-ui/index.js

And that file was just copied from https://github.com/system-ui/theme-ui/blob/master/packages/preset-tailwind/src/index.ts

Closing this issue as answered!
