### ISSUE TITLE
[gatsby-theme-minimal-blog-core]: add a `disableHomepage` flag

### ISSUE THREAD

**Issue by chmac** [LekoArts/gatsby-themes#307]
## Summary

Adding a flag called `disableHomepage` which disables the homepage component.

### Basic example

`disableHomepage` of type `boolean`, defaults to `false`

### Motivation

I want to manage my homepage in mdx. I've spent some time digging into this theme in order to be able to make changes. I had to shadow several templates, etc. But I still don't have a great way to do that, because I don't control the `createPage()` calls. Also, having two pages in gatsby with the same path is not such a great idea I guess.

Having an option to disable the inbuilt homepage would save me hacking the theme.

Thanks for this theme, it's super cool, saved me some time once I figured out how it all works!

**Comment by chmac** [comment]
Incidentally, for anybody who has a similar issue, I'm working around this with the awesome [patch-package](https://www.npmjs.com/package/patch-package) like so:

    patches/@lekoarts+gatsby-theme-minimal-blog-core+2.2.1.patch

```patch
diff --git a/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/gatsby-node.js b/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/gatsby-node.js
index 8add69a..d23db7b 100755
--- a/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/gatsby-node.js
+++ b/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/gatsby-node.js
@@ -261,7 +261,7 @@ exports.onCreateNode = ({ node, actions, getNode, createNodeId, createContentDig
 }
 
 // These template are only data-fetching wrappers that import components
-const homepageTemplate = require.resolve(`./src/templates/homepage-query.tsx`)
+// const homepageTemplate = require.resolve(`./src/templates/homepage-query.tsx`)
 const blogTemplate = require.resolve(`./src/templates/blog-query.tsx`)
 const postTemplate = require.resolve(`./src/templates/post-query.tsx`)
 const pageTemplate = require.resolve(`./src/templates/page-query.tsx`)
@@ -273,6 +273,7 @@ exports.createPages = async ({ actions, graphql, reporter }, themeOptions) => {
 
   const { basePath, blogPath, tagsPath, formatString } = withDefaults(themeOptions)
 
+  /* disable homepage
   createPage({
     path: basePath,
     component: homepageTemplate,
@@ -280,6 +281,7 @@ exports.createPages = async ({ actions, graphql, reporter }, themeOptions) => {
       formatString,
     },
   })
+  */
 
   createPage({
     path: `/${basePath}/${blogPath}`.replace(/\/\/+/g, `/`),
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
I don't feel like I should export every possible option as a public API and rather Gatsby itself should provide better ways to handle such stuff in regards to themes.

You could delete the page in your `gatsby-node.js` in the meantime:

```js
exports.onCreatePage = ({ page, actions }) => {
  const { deletePage } = actions

  if (
    page.componentChunkName === `component---themes-gatsby-theme-minimal-blog-core-src-templates-homepage-query-tsx`
  ) {
    deletePage(page)
  }
}
```

Will forward it internally so that we think about improving that in general.
