### ISSUE TITLE
[gatsby-theme-minimal-blog]: How to deactivate the "reading time" plugin

### ISSUE THREAD

**Issue by chronoclast** [LekoArts/gatsby-themes#323]
First of all, **congratulations for the amazing work!**
Sorry upfront for the (probably stupid/beginner) question, I really couldn't find an answer by myself.
Thanks a lot!!!
Viele Grüße aus Berlin!

## Summary

I would like to **deactivate / remove the "reading time" plugin**, so it's not shown in the blog posts; the one shown below, I mean:

![Screenshot 2020-03-25 at 12 33 18](https://user-images.githubusercontent.com/14571485/77534717-73331280-6e99-11ea-9293-c45ca8635cc5.jpg)

## Relevant information

I was going through [this documentation](https://www.gatsbyjs.org/packages/gatsby-remark-reading-time/), but I couldn't find such package or configuration (or a similar one) used in the project.

### Theme

I'm using the `gatsby-theme-minimal-blog`.

**Comment by compliment** [comment]
Remove timeToRead parts in @lekoarts/gatsby-theme-minimal-blog/src/components/post.tsx and shadow it.

**Comment by chronoclast** [comment]
@compliment thank you so much!

**All good now!**
I guess I couldn't find it across all files, since I was looking for `readingTime` instead of `timeToRead`. Damn... 😅

**Comment by LekoArts** [comment]
Thanks for the comment @compliment !

**Comment by ChristianIvicevic** [comment]
@LekoArts I noticed that using the starter however does not show any timeToRead whatsover. Even on a fresh bootstrap.

**Comment by LekoArts** [comment]
@ChristianIvicevic https://minimal-blog.lekoarts.de/introduction-to-defence-against-the-dark-arts and https://github.com/LekoArts/gatsby-themes/blob/master/cypress/e2e/minimal-blog.ts#L92 is both using the starter and it shows up / the test passes, so this is probably something on your end.
