### ISSUE TITLE
[gatsby-starter-minimal-blog]: Can't modify theme name

### ISSUE THREAD

**Issue by rust-rs** [LekoArts/gatsby-themes#324]
## Description

Can't modify the Header Title ('Lupin') since the `gatsby-config.js` is in `node_modules` and `node_modules` are ignored by `.gitignore` and so Netlify always show "Lupin" even though I changed it. 

How can I change the title ? 

### Expected result
Change title to whatever I want. 

### Environment

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.1
  npmPackages:
    gatsby: ^2.13.3 => 2.20.2
    gatsby-plugin-google-analytics: ^2.1.4 => 2.2.0
    gatsby-plugin-manifest: ^2.2.3 => 2.3.1
    gatsby-plugin-netlify: ^2.1.3 => 2.2.0
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sitemap: ^2.2.19 => 2.3.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8
  npmGlobalPackages:
    gatsby-cli: 2.11.2

**Comment by simonpeterdebbarma** [comment]
You are supposed to shadow the file you want to edit. You do not edit it in the node modules dir. Follow instructions in the README.

Take a read through this: https://www.gatsbyjs.org/docs/themes/shadowing/

**Comment by rust-rs** [comment]
@simonpeterdebbarma Thank you, but how do I apply it to my case ? I'm so lost right now...

**Comment by simonpeterdebbarma** [comment]
@rust-rs  Found out you don't need to shadow for changing that.

The title is coming from the `gatsby-config.js` file. This theme reads the config file for certain information.

![image](https://user-images.githubusercontent.com/31207418/77864899-9d156d80-71e8-11ea-945c-c5b2cbbe8eaa.png)

Edit the `siteTitle` field to whatever you want.

**Comment by rust-rs** [comment]
@simonpeterdebbarma This is exactly what I did (and by the way, I had dig deep into node_modules to find that file, which doesn’t make things easy)

But the problem is when I edit siteTitle and deploy it to netlify, well, it still show the old title.

**Comment by simonpeterdebbarma** [comment]
@rust-rs Sorry can't help you in that case. I changed that and it worked on my Netlify deployment.

@LekoArts could suggest something.

**Comment by rust-rs** [comment]
@simonpeterdebbarma maybe should I try the shadowing stuff ?

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You're not supposed to change stuff in your `node_modules` folder as this will only ever work locally on that one computer you're using. Netlify doesn't know about this.

The answer to your question is documented here: https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog#additional-configuration

Override the `siteTitle` property and you'll have your own title :)

Closing this as answered, thanks for using the theme!
