### ISSUE TITLE
[minimal-blog]: favicon not using path prefix 

### ISSUE THREAD

**Issue by FrederikS** [LekoArts/gatsby-themes#335]
Hey LekoArts,

First of all thanks for your beautiful themes - I really like them!

In case one wants to deploy a theme via github pages, its necessary to work with the path prefix for repo pages (https://www.gatsbyjs.org/docs/path-prefix/). As far as I know the favicon for all themes are placed in the SEO component e.g.:
https://github.com/LekoArts/gatsby-themes/blob/95fbdda698b33fb42378ed6e36c91518cb52ef52/themes/gatsby-theme-minimal-blog/src/components/seo.tsx#L59-L61

Since the `withPrefix` helper (https://www.gatsbyjs.org/docs/path-prefix/#add-the-path-prefix-to-paths-using-withprefix) is not used here, it is not working for when a path prefix is configured.

I could think of two ways to fix it. Obviously the usage of the `withPrefix` helper can be added here or it might be also an option to completely remove it from the SEO component and let [gatsby-plugin-manifest](https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/) do the work.

What do you think?

Cheers,
Frederik

**Comment by LekoArts** [comment]
Thanks for the report, fixed it with `withPrefix()`

**Comment by FrederikS** [comment]
Thanks for the quick fix!
