### ISSUE TITLE
[gatsby-theme-emma]: PerformanceObserver is undefined when attempting to connect to website in Internet Explorer

### ISSUE THREAD

**Issue by manyfacedman1** [LekoArts/gatsby-themes#337]
## Description
When the theme is loaded in Edge and InternetExplorer, the error 'PerformanceObserver is undefined' is thrown.  I'm not sure what to do honestly.  I'd appreciate any help.  Thanks
### Expected result

The page should load normally.
### Actual result

The browser begins rendering the page, but immediately destroys the layout. The error in the console is:
1-time: HTML1300,
2-times: ReferenceError: 'PerformanceObserver' is not defined, 
1-time: SCRIPT5009: SCRIPT5009: 'PerformanceObserver' is not defined

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.1
  npmPackages:
    gatsby: ^2.13.72 => 2.20.8 
    gatsby-plugin-google-analytics: ^2.1.8 => 2.2.2 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.6 => 2.3.3 
    gatsby-plugin-netlify: ^2.1.6 => 2.2.1 
    gatsby-plugin-offline: ^2.2.7 => 2.2.10 
    gatsby-plugin-page-progress: ^2.0.16 => 2.0.16 
    gatsby-plugin-sitemap: ^2.2.7 => 2.3.1 
    gatsby-remark-images-medium-zoom: ^1.4.0 => 1.4.0 
    gatsby-transformer-remark: ^2.7.1 => 2.7.1 
  npmGlobalPackages:
    gatsby-cli: 2.10.0

**Comment by LekoArts** [comment]
IE doesn't support `PerformanceObserver`: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver (some library inside the theme must use it)

You can polyfill it so that it works:
https://www.gatsbyjs.org/docs/browser-support/#polyfills
https://github.com/fastly/performance-observer-polyfill

Hope that helps!
