### ISSUE TITLE
Can we change the blogPath

### ISSUE THREAD

**Issue by vchrombie** [LekoArts/gatsby-themes#344]
## Summary

I have been using the [gatsby-starter-minimal-blog](https://github.com/LekoArts/gatsby-starter-minimal-blog) and this is the repo, https://github.com/vchrombie/blog.

I understand that the default `blogPath` for generating the lost of blogs is `/blog` from [here](https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog#usage). I would like to ask if there is any way to change to change it.

## Relevant information

I have the template hosted with GitHub pages. Right now, the list of blogs is at https://vchrombie.github.io/blog/blog. I would like to have it like https://vchrombie.github.io/blog/archive. 

Just want to know if it is possible.

### Theme

gatsby-starter-minimal-blog

### Environment (if relevant)

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 74.0.1
  npmPackages:
    gatsby: ^2.13.3 => 2.20.17 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.2.2 
    gatsby-plugin-manifest: ^2.2.3 => 2.3.3 
    gatsby-plugin-netlify: ^2.1.3 => 2.2.1 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-sitemap: ^2.2.19 => 2.3.1 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.11.7

### File contents (if changed)

`gatsby-config.js`: https://github.com/vchrombie/blog/blob/master/gatsby-config.js 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi! Thanks for using my theme :)

Sure, it's one of the theme options you can change.

```js
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: `@lekoarts/gatsby-theme-minimal-blog`,
      options: {
        blogPath: `/archive`,
      },
    },
  ],
};
```

This should work 👍

**Comment by vchrombie** [comment]
@LekoArts 
Thank you so much. It worked like charm. :smile: 

I loved the theme. It is really awesome.
