### ISSUE TITLE
List of site using LekoArt theme in productions

### ISSUE THREAD

**Issue by SOHELAHMED7** [LekoArts/gatsby-themes#369]
I suggest to encourage user to share their website URL who use LekoArt theme in production.

Something like - https://github.com/nestjs/nest/issues/1006

E.g. sixian.li

https://www.gregjopa.com/

**Comment by LekoArts** [comment]
Thanks for the issue and using my theme :)

If you use my theme you can share it on Twitter and tag me as I'm not so a fan of using issues for that.
