### ISSUE TITLE
(How) Can I add image(s) to a section in Cara theme?

### ISSUE THREAD

**Issue by Hrishikesh-K** [LekoArts/gatsby-themes#385]
### Theme

Cara
### Environment (if relevant)

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.2
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.20.36 => 2.21.0 
    gatsby-plugin-google-analytics: ^2.1.8 => 2.3.0 
    gatsby-plugin-manifest: ^2.2.6 => 2.4.0 
    gatsby-plugin-netlify: ^2.1.6 => 2.3.0 
    gatsby-plugin-offline: ^2.2.7 => 2.2.10 
```

### File contents (if changed)

`gatsby-config.js`: N/A
`package.json`: N/
`gatsby-node.js`: N/A
`gatsby-browser.js`: N/A
`gatsby-ssr.js`: N/A

Hello. I loved the Cara theme and would like to use it for a website. I was just wondering is there is way to add an image in a section. I can work with something like one image per section too. Also, if it's not too complicated, a simple HTML5 video support would also be great. Thanks.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You'll need to read this section: https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-cara#editing-the-content

You can use React components or normal HTML in MDX files. That's where you edit each section.

Hope that helps :)

**Comment by Hrishikesh-K** [comment]
Oh. I read the edit section before, I didn't know I could use HTML in MDX. I'll read more about it. Thanks for the quick help and once again thank you for this cool theme.
