### ISSUE TITLE
[Minimal Blog]: Selecting text in light mode makes it invisible.

### ISSUE THREAD

**Issue by PseudoCodeNerd** [LekoArts/gatsby-themes#389]
## Description

The issues arise while selecting text in *light* Minimal Blog. The text is therefore rendered invisible. Also, `Ctrl+A` makes the entire page (except the theme toggle) go blank. This may be due to a bug in CSS `::selection` property. 

Selecting / Highlighting content on dark mode works though.

### Steps to reproduce

Just select some text while in the light mode.

Also, try doing `Ctrl+A`

### Expected result

Selection against the white background should lead to the selected text being highlighted.

### Actual result

The selection made the selected text become white and thus render it invisible.

- Result of selecting landing paragraph.
![Bug](https://user-images.githubusercontent.com/33770878/80827059-e8180b80-8c00-11ea-9e21-1008200d7fef.png)

---

- Result of doing `Ctrl+A`
![Bug](https://user-images.githubusercontent.com/33770878/80827151-1564b980-8c01-11ea-9a81-e6a88e487e53.png)

### Environment

```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Languages:
    Python: 3.7.4 - /home/pseudocodenerd/anaconda3/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 75.0
  npmGlobalPackages:
    gatsby-cli: 2.12.7

```

**Comment by LekoArts** [comment]
Thanks, I fixed this in `@lekoarts/gatsby-theme-minimal-blog@2.3.2`
