### ISSUE TITLE
How can I add pages and a navigation menu to cara website?

### ISSUE THREAD

**Issue by arshiuh** [LekoArts/gatsby-themes#407]
I am going through your source code and it doesn't seem like there is a way to add pages to the current configuration.

I tried to create a pages folder within the src folder, but that does not work. Is there a plugin that is overriding the src folder?

Note: please do not close the issue before I respond back. Thank you.

**Comment by LekoArts** [comment]
Hi!

Can you give some more details about what's not working with `src/pages` creation? My codesandbox is working fine here: https://codesandbox.io/s/cara-multiple-pages-w7p7i?file=/src/pages/page-2.js

**Comment by ahmadihamid** [comment]
> Hi!
> 
> Can you give some more details about what's not working with `src/pages` creation? My codesandbox is working fine here: https://codesandbox.io/s/cara-multiple-pages-w7p7i?file=/src/pages/page-2.js

Could I use another theme here?

**Comment by LekoArts** [comment]
Will close this answered, thanks for the issue!
