### ISSUE TITLE
Where Is Previous Theme Layout?

### ISSUE THREAD

**Issue by BayuAngora** [LekoArts/gatsby-themes#410]
![gatsby-starter-minimal-blog-1000](https://user-images.githubusercontent.com/16639529/83467624-b36bce00-a4a4-11ea-84a6-e918913fba94.png)

Where is this theme?

**Comment by LekoArts** [comment]
Hi! Thanks for the issue!

You can find the previous version in the commit history of the starter. This would be the last iteration of that version:

https://github.com/LekoArts/gatsby-starter-minimal-blog/tree/69070f7d36d804acda19396012255a7f4fdd3720

As per https://stackoverflow.com/questions/3555107/git-clone-particular-version-of-remote-repository you could clone the repository, reset your HEAD to that commit and push this version to a repository of yours.

I'll close this as answered :)
