### ISSUE TITLE
Gatsby cara theme build is giving blanck screen

### ISSUE THREAD

**Issue by AtiqGauri** [LekoArts/gatsby-themes#411]
## Summary
Cara theme build (static site inside public folder) giving blank screen in browser and github pages while gatsby develop and gatsby build command are working fine.
I am able to see website with develop command and changes are reflecting too.

## Relevant information
I did edited intro.mdx file to replace my name 

### Theme
CARA

### File contents (if changed)

`gatsby-config.js`: 
``` 
require(`dotenv`).config({
  path: `.env`,
})

module.exports = {
  siteMetadata: {
    // You can overwrite values here that are used for the SEO component
    // Of course you can also add new values here to query them like usual
    // See all options: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-cara/gatsby-config.js
    siteTitleAlt: `Anant Jain`,
  },
  plugins: [
    {
      resolve: `@lekoarts/gatsby-theme-cara`,
      // See the theme's README for all available options
      options: {
      	basePath: `/sideproject`
      },
    },
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: process.env.GOOGLE_ANALYTICS_ID,
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Cara - @lekoarts/gatsby-theme-cara`,
        short_name: `Cara`,
        description: `Playful and Colorful One-Page portfolio featuring Parallax effects and animations`,
        start_url: `/`,
        background_color: `#141821`,
        theme_color: `#f6ad55`,
        display: `standalone`,
        icons: [
          {
            src: `/android-chrome-192x192.png`,
            sizes: `192x192`,
            type: `image/png`,
          },
          {
            src: `/android-chrome-512x512.png`,
            sizes: `512x512`,
            type: `image/png`,
          },
        ],
      },
    },
    `gatsby-plugin-offline`,
    `gatsby-plugin-netlify`,
  ],
}
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

If you want to see the result of a `gatsby build` you'll need to use `gatsby serve`.
For instructions on how to use GitHub pages with Gatsby you should follow these instructions: https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/

Will close this as answered!

**Comment by AtiqGauri** [comment]
Yes I did tried it with gatsby serve and it was working fine then...

Then as mentioned in [instructions ](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/) I tried it on gh-pages and master.
I have added pathPrefix variable in gatsby-config.js

![Screenshot (158)](https://user-images.githubusercontent.com/37737221/83879801-dbd12200-a75b-11ea-9643-371bc538d1e8.png)

**But still I see blank page on github url (tried on master and gh-pages)** 


![Screenshot (157)](https://user-images.githubusercontent.com/37737221/83879880-facfb400-a75b-11ea-8657-80ba707a45d6.png)

**Comment by LekoArts** [comment]
The instructions say this:

> Make sure that your repository’s settings has the gh-pages branch set as the source to deploy from.

So you shouldn't use `master`

**Comment by AtiqGauri** [comment]
I did make a gh-pages branch and deployed it with pathPrefix flag still it is showing blank screen
