### ISSUE TITLE
[gatsby-theme-minimal-blog]: Comments in MDX code blocks are with different size than other elements on iOS devices

### ISSUE THREAD

**Issue by belev** [LekoArts/gatsby-themes#414]
## Description

When using a longer comment in MDX code blocks, the font size and height of the comment are not with proper size. The comment is bigger than every other texts

### Steps to reproduce

Add a longer comment in some MDX code block. For example `// some comment here but if it is long enough it is broken"`

### Expected result

The size of the comment should be with the size of all other text.

### Actual result

Size of the comment is not with the same size. In the screenshot below can be seen better:
<img width="363" alt="Screenshot 2020-06-07 at 17 23 15" src="https://user-images.githubusercontent.com/5807771/83971533-63e23380-a8e4-11ea-850d-5b8ecb90cbca.png">

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I followed your reproduction steps but don't see anything wrong?

![image](https://user-images.githubusercontent.com/16143594/84126554-58a31b00-aa3e-11ea-9668-4d5d4bd14c0c.png)

Can you please share a reproduction project where I'd see this behavior?

**Comment by belev** [comment]
Hi,

Yes, sure. The problem occurs only on iOS device (I tested it on iPhone 7). It can be tested on simulator as well, it was reproducible there as well.

Please let me know if this helps or if I should provide more information.

**Comment by LekoArts** [comment]
Fixed in `@lekoarts/gatsby-theme-minimal-blog@2.3.8`

**Comment by belev** [comment]
Thank you very much.
