### ISSUE TITLE
How to change footer content?

### ISSUE THREAD

**Issue by chirag80** [LekoArts/gatsby-themes#419]
Is there a way to change footer content in **Gatsby Starter Portfolio: Cara** ? I want to change "Copyright © 2020. All rights reserved" text.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You'll need to [shadow](https://www.gatsbyjs.org/docs/themes/shadowing/) the footer file by creating a file at `<your-project-root>/src/@lekoarts/gatsby-theme-cara/components/footer.jsx` with the contents of [the original file](https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-cara/src/components/footer.tsx). This way you override the footer that comes from the theme. Then you can modify the contents to your liking.

Thanks for using the theme, will close this as answered!

**Comment by chirag80** [comment]
Thank you for your reply! I placed footer.jsx file as you suggested to shadow the footer content. I am getting an error 'Error: [useColorMode] requires the ColorModeProvider component' after adding footer.jsx original file. seems error is caused by useColorMode hook.  if i remove dark mode toggle button and related implementation then it works. i can see updated footer content. Can you please help!
