### ISSUE TITLE
ColorModeProvider error after Shadowing footer.tsx - gatsby-theme-cara

### ISSUE THREAD

**Issue by chirag80** [LekoArts/gatsby-themes#420]
Hi, Thanks for making such a great theme and starter project.

I am customizing gatsby-starter-portfolio-cara for my portfolio app. I want to change footer content. As suggested https://github.com/LekoArts/gatsby-themes/issues/419, I shadowed footer.tsx in my working directory. Now i am getting 'Error: [useColorMode] requires the ColorModeProvider component' . It works if i remove the code from footer.tsx related to dark mode toggle button. Looks like error is due to some version conflict?  I am using "@lekoarts/gatsby-theme-cara": "^1.2.5" and "gatsby": "^2.20.36". 

I also found similar issue posted on theme-ui https://github.com/system-ui/theme-ui/issues/971 . but couldn't figure out the exact solution

my project on github - https://github.com/chirag80/gatsby-portfolio

**Comment by LekoArts** [comment]
This is an upstream issue: https://github.com/gatsbyjs/gatsby/issues/24888
https://github.com/gatsbyjs/gatsby/issues/24653

You'll need to wait for a fix from the PR: https://github.com/gatsbyjs/gatsby/pull/24810

In the meantime you can use yarn's `resolutions` feature like explained here: https://github.com/system-ui/theme-ui/issues/971#issuecomment-640159475

This will set all Theme UI versions to the same one.
