### ISSUE TITLE
[minimal-blog]: 301 from introduction-to-defence-against-the-dark-arts to introduction-to-defence-against-the-dark-arts/

### ISSUE THREAD

**Issue by larsroettig** [LekoArts/gatsby-themes#424]
## Description

Any Blogsite is redirected from URL without / to URL with additional /

![2020-06-14_19-47](https://user-images.githubusercontent.com/5289370/84600251-4da21d80-ae78-11ea-8fc7-63b086639e8d.png)

### Steps to reproduce
Open Browser console:
- https://minimal-blog.lekoarts.de/introduction-to-defence-against-the-dark-arts
- you see 301

### Expected result

There should be no *301* is bad for SEO

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
You can follow the upstream issue: https://github.com/gatsbyjs/gatsby/issues/9207
