### ISSUE TITLE
[gatsby-theme-minimal-blog]: Creating new content types (nodes) + corresponding pages

### ISSUE THREAD

**Issue by cesards** [LekoArts/gatsby-themes#427]
Hi again!

## "Summary"

I'm trying to create new content types apart from the ones provided in your theme (MdxPost & MdxPage):

Let's call these new content types `MdxBook` and `MdxProject`. As you can imagine, these new content types' purpose is very similar to the `MdxPost` one since I want to provide a list of books and projects with their page creation, respectively.

I've been playing around the Gatsby Node APIs and I think I understand at least 50% of what's being done [in here](https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog-core/gatsby-node.js)

Since both new contents are base on Markdown files, I didn't need to create new types, just add new fields to the Mdx header:
```
---
type: book
title: "Title"
description: "Random description."
rating: 3
goodreads-review: https://www.goodreads.com/review/show/3135270300
tags: [...]
cover: "/get-out-your-own-way.jpg"
---
```

The problem comes when creating pages for this type of node, because I'm putting books in a different path (specified in the `gatsby-config` file:
```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `books`,
        path: `content/books`, // Folder path.
},
```

Since the path is different from the rest of `Mdx` nodes (you do a check [here](https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L196) and [here](https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L237) I don't think the nodes are created and I'm not sure how [`createPages`](https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L271) works (it seems advanced level and I'm new to Gatsby).

In my `gatsby-node.js` I added a `slug` field because if I understood well, this is the one that's going to get the node's page created:

```
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNode, createNodeField } = actions

  // Make sure that it's an MDX node
  if (node.internal.type !== `Mdx`) {
    return
  }

  const fileNode = getNode(node.parent)
  const source = fileNode.sourceInstanceName

  // Check for "books" and create the "Book" type
  if (node.internal.type === `Mdx` && source === 'books') {
    // Add slug field for books.
    const slug = createFilePath({ node, getNode, basePath: `books` })
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
}
```
And the query shows the slug:
```
{
  "data": {
    "allMdx": {
      "edges": [
        {
          "node": {
            "fields": {
              "slug": "/2020/2020-02-01-book-ttest/"
            }
          }
        },
        {
          "node": {
            "fields": {
              "slug": "/2020/June/get-out-of-your-own-way/"
            }
          }
....
```
but it seems that the url is not created for those node types. I've tried navigating to:
- http://localhost:8000/books/2020/June/get-out-of-your-own-way
- http://localhost:8000/2020/June/get-out-of-your-own-way
- http://localhost:8000/books/get-out-of-your-own-way
- http://localhost:8000/get-out-of-your-own-way
and I got nothing.

**I guess I have 2 questions:**

**1. What's the procedure you would suggest when trying to add new content types?**
(is it possible to add behavior to the `gatsby-node.js` declared in the theme? If not, would you suggest shadowing that file into my theme?)

**2. Any suggestions on what I'm doing wrong to get pages created for those new nodes?**

Thank you so much in advance, I hope this question might be helpful for other people using your theme. I'm planning to write a blog post about the whole process of creating a Gatsby site at some point, and I'll definitely mention the great job you've done with it. 

### Theme

[gatsby-theme-minimal-blog]

**Comment by LekoArts** [comment]
Hi!

I've set up a repository showing you an example: https://github.com/LekoArts/minimal-blog-new-content-type
This commit is adding the "Book" content type: https://github.com/LekoArts/minimal-blog-new-content-type/commit/985895b4984b9e6f8976b9bcfbf0f79e32900f21

You were on the right track, but some essential parts were missing. To explain the commit a bit:

---

1) Set up the new content source:

```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `books`,
        path: `content/books`
      }
    },
```

2) Fill it with some content

3) Create a new generic interface called `Book` so that we can query for it:

```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions

  createTypes(`
    interface Book @nodeInterface {
      id: ID!
      slug: String!
      type: String!
      title: String!
      rating: Int!
      excerpt(pruneLength: Int = 160): String!
      body: String!
      html: String
      timeToRead: Int
      tags: [String]
      cover: File @fileByRelativePath
      description: String
    }
    
    type MdxBook implements Node & Book {
      slug: String!
      title: String!
      type: String!
      rating: Int!
      excerpt(pruneLength: Int = 140): String! @mdxpassthrough(fieldName: "excerpt")
      body: String! @mdxpassthrough(fieldName: "body")
      html: String! @mdxpassthrough(fieldName: "html")
      timeToRead: Int @mdxpassthrough(fieldName: "timeToRead")
      tags: [String]
      cover: File @fileByRelativePath
      description: String
    }
  `)
}
```

This is the same concept as here: https://github.com/LekoArts/gatsby-themes/blob/d62857ffd1d2d97cfa31cb6ca37cb39db48467d0/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L38-L139

You explicitly define which fields the interface and type will have, later in the `onCreateNode` stage you'll fill these with values.

4) Create those nodes (the `MdxBook` one) and connect it in a child-parent relationship to the `Mdx` type

```js
exports.onCreateNode = ({ node, actions, getNode, createNodeId, createContentDigest }) => {
  const { createNode, createParentChildLink } = actions

  // Make sure that it's an MDX node
  if (node.internal.type !== `Mdx`) {
    return
  }

  // Create a source field
  // And grab the sourceInstanceName to differentiate the different sources
  // In this case "postsPath" and "pagesPath"
  const fileNode = getNode(node.parent)
  const source = fileNode.sourceInstanceName

  // Check for "posts" and create the "Post" type
  if (node.internal.type === `Mdx` && source === 'books') {
    const fieldData = {
      slug: node.frontmatter.slug ? node.frontmatter.slug : createFilePath({ node, getNode, basePath: "books" }),
      title: node.frontmatter.title,
      type: node.frontmatter.type,
      rating: node.frontmatter.rating,
      tags: node.frontmatter.tags,
      cover: node.frontmatter.cover,
      description: node.frontmatter.description,
    }

    const mdxBookId = createNodeId(`${node.id} >>> MdxBook`)

    createNode({
      ...fieldData,
      // Required fields
      id: mdxBookId,
      parent: node.id,
      children: [],
      internal: {
        type: `MdxBook`,
        contentDigest: createContentDigest(fieldData),
        content: JSON.stringify(fieldData),
        description: `Mdx implementation of the Book interface`,
      },
    })

    createParentChildLink({ parent: node, child: getNode(mdxBookId) })
  }
}
```

Interesting bit here is the `slug`:

```js
slug: node.frontmatter.slug ? node.frontmatter.slug : createFilePath({ node, getNode, basePath: "books" }),
```

If it's not defined in the frontmatter the filepath will be used.

5) The rest is the usual querying, page creation, React components etc.

---

Hope that helps!

Alternatively - if you don't want to create the `Book` interface - you could also skip that part and filter the `allMdx` query by the path:

![image](https://user-images.githubusercontent.com/16143594/86362887-3df74700-bc76-11ea-9b36-262163a98e7a.png)

In the `exports.createPages` step you then would use `fields.slug` (with your `onCreateNode` logic)

**Comment by cesards** [comment]
Hey LekoArts! Sorry I didn't get to answer you before. This is great!! Thank you so much! I went ahead and implemented it the way you just mentioned. I'll have a quick look to the repo you created but this is great. Thank you so much for this, it's really helpful! <3
