### ISSUE TITLE
Default the theme to start in "dark" mode

### ISSUE THREAD

**Issue by gbailey4** [LekoArts/gatsby-themes#434]
## Summary
I prefer dark mode for my readers but would still like them to have the option to change to light mode.

### Theme
Minimal

### Question
Is there a simple way to set the default theme setting to dark? I've read through a few issues here but I'm still unclear on how to do so.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

This question really boils down to a question about Color Modes in Theme UI: https://theme-ui.com/color-modes
You'll want to switch the modes. You can do that by creating a file at `<your-root>/src/gatsby-plugin-theme-ui/index.js` with the following contents:

```js
import { merge } from "theme-ui"
import { tailwind } from "@theme-ui/presets"
import originalTheme from "@lekoarts/gatsby-theme-minimal-blog/src/gatsby-plugin-theme-ui/index"

const theme = merge(originalTheme, {
  initialColorModeName: 'dark',
  colors: {
    text: tailwind.colors.gray[4],
    primary: tailwind.colors.purple[5],
    secondary: `#7f8ea3`,
    toggleIcon: tailwind.colors.gray[4],
    background: `#1A202C`,
    heading: tailwind.colors.white,
    divide: tailwind.colors.gray[8],
    muted: tailwind.colors.gray[8],
    modes: {
      light: {
        text: tailwind.colors.gray[8],
        primary: tailwind.colors.purple[7],
        secondary: `#5f6c80`,
        toggleIcon: tailwind.colors.gray[8],
        background: tailwind.colors.white,
        heading: tailwind.colors.black,
        divide: tailwind.colors.gray[4],
        muted: tailwind.colors.gray[3],
      }
    }
  }
})

export default theme
```

This switches the `dark` color mode to be the default and `light` to be an additional mode. In the original theme the light mode implicitly uses some colors from the `tailwind` preset (e.g. the `background`) so in this case you explicitly have to define it.

**Comment by gbailey4** [comment]
Thank you so much @LekoArts ! That worked great. Strangely, it doesn't show in `gatsby develop`, but on deploy it works as expected.

One thing I'm wondering from here - is the `initialColorModeName` exposed anywhere? I'm styling a form on a custom contact page and would like to have the form inputs change color based on the color mode.

**Comment by LekoArts** [comment]
> Strangely, it doesn't show in gatsby develop, but on deploy it works as expected.

You might have set it in the `localStorage` by flipping the switch a bunch, when you delete the key it might work:

![image](https://user-images.githubusercontent.com/16143594/86338494-b21ff380-bc52-11ea-994b-5309efda66ec.png)

> One thing I'm wondering from here - is the initialColorModeName exposed anywhere? I'm styling a form on a custom contact page and would like to have the form inputs change color based on the color mode.

As long as you style the form inputs with `sx` from Theme UI and use the colors it'll respect the color modes automatically. So if you e.g. use `text` for your `color` on the form, it'll switch that value with the color mode.

You can use the `useColorMode` hook to access the current mode:
https://theme-ui.com/api#usecolormode
