### ISSUE TITLE
Cara theme change factor/offset based on window size

### ISSUE THREAD

**Issue by devism** [LekoArts/gatsby-themes#435]
## Summary
Is it possible to change the factor and offset settings based on the window size of the browser? Kind of like doing a css media query. For example if I adjust the factor and offset and it looks good on mobile it needs a different adjustment on desktop. So maybe I could do something like
`if (window.innerWidth > "1024px"){
     offset={0.6} factor={1}
} else{
offset={1} factor={3}
}
`

### Theme
Cara theme

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Sure, you can change those values depending on the screen size like in any other React application. There are a bunch of libraries out there that provide utils/hooks to set the different states.

Here's a concrete example with `browser-monads`: https://github.com/LekoArts/gatsby-themes/issues/423#issuecomment-652299452
