### ISSUE TITLE
MDX outside of src/pages does allow for graphQL queries

### ISSUE THREAD

**Issue by eskewj** [LekoArts/gatsby-themes#439]
I'm new to React and Gatsby and I love the minimal-blog theme.  However I don't want to use it for a blog.  I want to use it for a two-page site where I will need to pull in data.  I tried to put my query in one of the content/pages mdx files, however I run into this issue:

https://github.com/ChristopherBiscardi/gatsby-mdx/issues/187#issuecomment-437161966

I've tried instead to use a src/pages js file by adding the navigation item to gatsby-config.js and it does successfully link to the page and the query does work there, however now I'm missing the header + footer I had before when the page was in content/pages.

Is there a workaround such that I can use the src/pages dir for my site while still using the minimal-blog theme?

Thank you!

**Comment by thehapax** [comment]
I have the same issue as @eskewj . would be helpful to know. thanks in advance

**Comment by thehapax** [comment]
@eskewj, here is one way to pull in the header/footer Layout tag from the theme. 

```
import React from "react"
import Layout from "@lekoarts/gatsby-theme-minimal-blog/src/components/layout"

const HomePage = ({data}) => {
    return(
      <>
      <Layout>
        <div>
         This is a myapp.js page in the src/pages directory. 
        </div>
      </Layout>
      </>
    )
  }

export default HomePage
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You can follow https://github.com/gatsbyjs/gatsby/issues/19367 for progress on the upstream issue. Also thanks to @thehapax for the correct explanation. As correctly explained you can always import components from the theme itself and therefore re-use them in other parts.
