### ISSUE TITLE
Convert To Unibit Themes?

### ISSUE THREAD

**Issue by BayuAngora** [LekoArts/gatsby-themes#45]
Is there any plan to convert your Gatsby themes into unibit? 
https://www.stackbit.com/unibit/ 

So we can use it for multiple static generator such Hugo, Jekyll, etc?

**Comment by LekoArts** [comment]
Hi!

I don't plan on doing that. I'm certainly biased but I think Gatsby is superior to Hugo, Jekyll etc. so I want these themes to perform best with Gatsby -- I fear that with unibit I'm sacrificing latest features/best implementation for multi-platform support.

**Comment by JugglerX** [comment]
Hi Leko, I really admire your themes, I think you do great work. I just want to point out that you don't need to use the Unibit SSG to make your theme work with Stackbit. You can now add Stackbit to an existing native Gatsby theme. The process is described here https://docs.stackbit.com/uniform/
