### ISSUE TITLE
[gatsby-starter-minimal-blog]: Can't edit the hero text as instructed in the docs.

### ISSUE THREAD

**Issue by Jarmos-san** [LekoArts/gatsby-themes#451]
## Description

Thanks for sharing your themes, they're amazing & easy to use for someone who has no JS experience. So I can't change the default hero text following the default instructions provided in the documentation. 

### Steps to reproduce

I tried using your `gatsby-starter-minimal-blog`, downloaded it as instructed using the Gatsby CLI command `gatsby new [dirname] https://github.com/LekoArts/gatsby-starter-minimal-blog`. It downloads the necessary files & folders as-is from the [gatsby-starter-minimal-blog](https://github.com/LekoArts/gatsby-starter-minimal-blog) repository.

But the problem is I've no clue how to edit the default hero text. I tried following instructions provided in [Changing the "Hero" text](https://github.com/LekoArts/gatsby-starter-minimal-blog#changing-the-hero-text) but there's actually no `src` root directory in the repository itself.

You can find my repository for the project [over here](https://github.com/Jarmos-san/gatsby-blog). I pushed it without making any changes to it right after creating a new project using the Gatsby CLI command.

### Expected result

There should be a `hero.mdx` file somewhere in the project, so that the default hero text can be changed as per the requirements of the user. 

### Actual result

The `hero.mdx` file doesn't exist anywhere.

### Environment

```shell
System
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-2350M CPU @2.30GHz
    Shell: 5.0.16 - /bin/bash
Binaries:
    node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/14.5.0/bin/npm
Browsers:
    Firefox: 78.0.1
npmPackages:
    gatsby: ^2.20.36 => 2.24.2
    gatsby-plugin-google-analytics: ^2.1.4 => 2.3.11
    gatsby-plugin-manifest : ^2.2.3 => 2.4.18
    gatsby-plugin-netlify: ^2.1.3 => 2.3.11
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sitemap: ^2.2.19 => 2.4.11
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.10 => 1.1.10
npmGlobalPackages:
    gatsby-cli: 2.12.60
```

Once again thanks for sharing your work. If you could let me know if its something that I'm doing wrong, it would be wonderful!

**Comment by strdr4605** [comment]
Here is how I changed it 
https://github.com/strdr4605/strdr4605.github.io/blob/source/src/%40lekoarts/gatsby-theme-minimal-blog/texts/hero.mdx

**Comment by Jarmos-san** [comment]
> Here is how I changed it
> https://github.com/strdr4605/strdr4605.github.io/blob/source/src/%40lekoarts/gatsby-theme-minimal-blog/texts/hero.mdx

The core problem is the `hero.mdx` file doesn't exist anywhere. Heck, there's no `src` folder either! Of course, there're workarounds but I don't think so the workarounds are expected behavior. It might through someone else off-guard even after following the documentation word-to-word.

I just wanted to point it out, so if someone else who has the same issue can understand that there's a bug.

**Comment by LekoArts** [comment]
Hi, thanks for the issue and sorry to hear that you run into troubles.

As per the instructions you linked you're supposed to create that file on your own, e.g. in your favorite editor/IDE. The way that @strdr4605 did it isn't a workaround but the official way of overriding/shadowing files in Gatsby themes.

So go ahead and create the file at the location specified in the documentation and you'll be good to go :)

**Comment by Jarmos-san** [comment]
@LekoArts Appreciate the clarification.

**Comment by Nderim1** [comment]
> Here is how I changed it https://github.com/strdr4605/strdr4605.github.io/blob/source/src/%40lekoarts/gatsby-theme-minimal-blog/texts/hero.mdx

Hi @strdr4605 thanks for your answer. I am facing the same problem right now and wanted to check your link but seems it is expired. I know it is late but can you please update it? Or tell me how did you manage to change the hero text? It will be very helpful. Thank you

**Comment by strdr4605** [comment]
See https://github.com/strdr4605/strdr4605.github.io/blob/v1/src/@lekoarts/gatsby-theme-minimal-blog/texts/hero.mdx
