### ISSUE TITLE
[LekoArts/gatsby-starter-minimal-blog] - Cannot locate the `src` folder

### ISSUE THREAD

**Issue by mohammedasker** [LekoArts/gatsby-themes#460]
Hey, there! Let me start by saying that I absolutely love the themes you created and I'm looking forward to using it in my personal blog.

What I'm trying to do is to change the contents in the hero section as well as the logo and footer. My problem is I cannot locate the `src` folder in the `gatsby-starter-minimal-blog`. I did read the documentation and I'm not sure how I can implement the [changing the hero text](https://github.com/LekoArts/gatsby-starter-minimal-blog#changing-the-hero-text) part as I'm still relatively new to Gatsby and React in general.

Seeing two other issues like [this one](https://github.com/LekoArts/gatsby-themes/issues/415) and [that one](https://github.com/LekoArts/gatsby-themes/issues/439) suggests that there could be some way of accessing `src` files. The only clue I get so far is I have to do some "Shadowing" even though I'm not exactly sure what does this term mean.

Is there a way I can find the `src` folder so that I can change the things I want?

Thank you!

**Comment by magical-mishka** [comment]
I second this. I cannot link the src folder either. I keep going round and round this. Would be helpful if more explanation was given.

**Comment by svict4** [comment]
https://github.com/LekoArts/gatsby-themes/issues/451#issuecomment-657096750

**Comment by thehapax** [comment]
you can just add the src folder in the top level directory when you clone the `gatsby-starter-minimal-blog`

in the gatsby documentation - the file structure goes like this: 

src/
src/components
src/templates
src/pages

in the pages directory you can create .js pages

I'd recommend taking a look at the docs here: 
https://www.gatsbyjs.org/docs/themes/building-themes/#gatsby-theme-minimal

Although, it might be useful to have either 1) a note in the readme in the @LekoArts theme, or 2) mirror the directory structure of gatsby-default-starter or gatsby-theme-minimal so that it will be less confusing for new gatsby users. 

I agree, it must have taken me several hours to figure out what was missing in the @LekoArts/gatsby-starter-minimal-blog theme.

**Comment by HawiCaesar** [comment]
@mohammedasker it looks you have to create the exact directory structure `src/@lekoarts/gatsby-theme-minimal-blog/texts/hero.mdx`

It also took me a few moments to understand but this issue led me in the right direct.

**Comment by mohammedasker** [comment]
> @mohammedasker it looks you have to create the exact directory structure `src/@lekoarts/gatsby-theme-minimal-blog/texts/hero.mdx`
> 
> It also took me a few moments to understand but this issue led me in the right direct.

Yeah, that worked out. Literally creating the exact file structures solved the problem. Does that mean if I want to change the logo, favicon, projects, and footers; I also have to do the same thing for them as well?

**Comment by eskewj** [comment]
To change the header / footer you'd shadow the components here: 
`src/@lekoarts/gatsby-theme-minimal-blog/components`
Favicons would go in the `static` dir.

**Comment by timschuetz** [comment]
I have two questions about modifying the theme. Here is my [GitHub Repository ](https://github.com/timschuetz/tschuetz) and the [website](https://tschuetz.netlify.app) deployed via Netlify.

1) **Adding pages:** I created pages and added them to the navigation in the gatsby-config.yml in the root folder. Why are they not being displayed in the navigation bar?

2) **Changing the footer**: I created a folder in src/@lekoarts/gatsby-theme-minimal-blog/components like @eskewj suggested. However I don't understand what kind of file goes in there. I found a footer.jsx file in the theme's "lekoarts" folder which I modified.  But I got a failed deploy when I added it to my repo.  I deleted it again.   So what do I need to do?

**Comment by timschuetz** [comment]
Update: 

Chrome seemed to load an old version of the website. A few changes I made in the `gatsby-config.js` now appear in the navigation.

However, I still could not get the SiteTitle to display my name. Could someone take a look at my [config](https://github.com/timschuetz/tschuetz/blob/master/gatsby-config.js) and tell me what I am missing? 

I'm also still trying to figure out how I can get the [footer](https://github.com/timschuetz/tschuetz/tree/master/src/%40lekoarts/gatsby-plugin-theme-ui/components) I created to work. Is this shadowed correctly in the /src ?

**Comment by dboston528** [comment]
I've followed all the instructions in the above comments and still can't seem to change any of the text in the hero section. I've also read up on shadowing and overriding, and still can't seem to get it. Is there a better explanation out there? I really like this theme and don't want to give up on using it.

**Comment by dboston528** [comment]
**Update: **
I figured it out. I just had restart my development server and the suggestions above worked out fine.
