### ISSUE TITLE
Adding a 404 page with Cara background SVGs and theme

### ISSUE THREAD

**Issue by j1nma** [LekoArts/gatsby-themes#47]
HI! My intention is as the title says... I am new to GatsbyJS. I am sorry if this is not the place for this kind of questions.

Right now I have the following structure.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/19524560/63162689-9dfee380-bff9-11e9-9876-920297dd2e14.png">

404.js just exports a <NotFound /> component (notfound.js) where I would like to add the SVG and preserve the general theme, plus adding a Back to Home button, as I see in the inner files from node_modules directory.

**Comment by LekoArts** [comment]
Thank you for opening this and sorry for taking so long!

In the meantime of you creating this issue and now I changed up the Cara theme a bunch.

You can import the `Layout` component for the general CSS and SEO. Import `Parallax` like in the [index](https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-cara/src/templates/cara.tsx) file. Then I'd probably copy a section like [Hero](https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-cara/src/components/hero.tsx) and change up the content.

I'm marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion.
