### ISSUE TITLE
How to change the favicon icon in the header

### ISSUE THREAD

**Issue by SrajanKumarShukla** [LekoArts/gatsby-themes#476]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Please fill out the issue template, I sadly don't know what you're talking about. Thanks!

**Comment by LekoArts** [comment]
Will close this as stale, please reply with a filled out template if you still need help.
