### ISSUE TITLE
changing default color mode for gatsby-theme-cara

### ISSUE THREAD

**Issue by copocaneta** [LekoArts/gatsby-themes#478]
First of all thank you for this amazing design and for your time.

I am trying to figure out how to change the default color mode for gatsby-theme-cara? 

I tried shadowing:

node_modules/@lekoarts/gatsby-theme-cara/src/gatsby-plugin-theme-ui/index.js 

to

src/@lekoarts/gatsby-theme-cara/gatsby-plugin-theme-ui

and changing:

`initialColorModeName: `dark`,`

to

`initialColorModeName: `light`,`

with no success

also tried changing:

```
  colors: {
    primary: tailwind.colors.orange[4],
    secondary: tailwind.colors.indigo[6],
    text: tailwind.colors.gray[3],
    heading: tailwind.colors.white,
    background: `#ffffff`,
```

but that didnt work either.

Could you please point me to the right direction?

Thanks in advance.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Changing the Theme UI config is special as you'll need to place the file at `src/gatsby-plugin-theme-ui/index.js`. I'll also point to this issue (https://github.com/LekoArts/gatsby-themes/issues/434) where I explained how to switch the mode. TL;DR is that just by changing the `initialColorModeName` you don't change it, you merely change the name of the initial color mode. So by swapping the values for the modes, you can switch the default mode.
