### ISSUE TITLE
[minimal-blog]: Copy button horizontal scroll

### ISSUE THREAD

**Issue by LekoArts** [LekoArts/gatsby-themes#479]
## Description

When the code block horizontally scrolls (on the iPhone) the copy button stays in its position and not in the top right.

### Expected result

Should stay in top right

### Actual result

When you scroll it changes it position

<img width="479" alt="Bildschirmfoto 2020-08-28 um 17 34 17" src="https://user-images.githubusercontent.com/16143594/91585741-bddb1e00-e954-11ea-9397-131185c702d8.png">

**Comment by sh-cho** [comment]
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/11611397/198682631-bfb2f283-7cb4-43f6-845a-ce34ddeab855.png">

@LekoArts Hi, looks like it's happening again.

Can you check?

ex) https://minimal-blog.lekoarts.de/code-block-examples

**Comment by LekoArts** [comment]
Thanks @sh-cho 👍 This should be fixed in `@lekoarts/gatsby-theme-minimal-blog@5.0.2`
