### ISSUE TITLE
[minimal-blog] Horizontal scrolling for long words 

### ISSUE THREAD

**Issue by SOHELAHMED7** [LekoArts/gatsby-themes#492]
## Summary

When a word in blog or tag or similar places is too long for e.g. some link `https://gist.github.com/SOHELAHMED7/1a8429d57f9f264eb40b6cfce87439f61a8429d57f9f264eb40b6cfce87439f61a8429d57f9f264eb40b6cfce87439f61a8429d57f9f264eb40b6cfce87439f61a8429d57f9f264eb40b6cfce87439f61a8429d57f9f264eb40b6cfce87439f61a8429d57f9f264eb40b6cfce87439f61a8429d57f9f264eb40b6cfce87439f61a8429d57f9f264eb40b6cfce87439f6` Horizontal scroll appears in the browser in both mobile and desktop

Screeshots: 
![horiz-scroll](https://user-images.githubusercontent.com/6770119/93888345-85392500-fd05-11ea-870d-ab842a641369.png)

### Theme

minimal-blog. Version - 2.5.2

If need more info, feel free to let me know

Thank you.

**Comment by LekoArts** [comment]
Was a simple CSS fix :)

```
Successfully published:
 - @lekoarts/gatsby-theme-minimal-blog@2.6.1
```

**Comment by SOHELAHMED7** [comment]
I request to add this CSS style to places where tags are shown. For e.g. 

 - blog list page, 
 - tag list page, 
 - a page for all blog with a particular tag, 
 - a blog post

because currently I have a test tag that is bit long without any space character and that introduce horizontal scrolling to the website.

**Comment by LekoArts** [comment]
In my opinion you can add this CSS on your own then, having such a long tag without a space seems like an edge-case.
