### ISSUE TITLE
[gatsby-theme-specimens]: Broken live preview

### ISSUE THREAD

**Issue by lguima** [LekoArts/gatsby-themes#495]
## Description

The live preview site of `gatsby-theme-specimens` is broken.

### Steps to reproduce

Access the live preview site of `gatsby-theme-specimens`: https://specimens.lekoarts.de/

### Expected result

The live preview should render the theme.

### Actual result

The live preview is not rendering the theme.

### Environment

Live preview.

### Evidence

![gatsby-live-preview](https://user-images.githubusercontent.com/1562097/94342220-f3bc0280-ffe5-11ea-83d6-e6c182f9a8a7.PNG)

**Comment by LekoArts** [comment]
Thanks for the issue! This is coming from https://github.com/gregberge/loadable-components/issues/629 - in the meantime I'm pinning to version `5.13.1` and it works now again.
