### ISSUE TITLE
[minimal-blog]: Provide ability to turn off Google Analytics Gatsby Plugin

### ISSUE THREAD

**Issue by aleccool213** [LekoArts/gatsby-themes#499]
## Summary

Some users (me 😇) would like to disable Google Analytics. I use a different service.

### Basic example

New gatsby config option maybe titled `enable-google-analytics` with the default being true to provide backwards compatibility. 

### Motivation

I host my own analytics service.

**Comment by LekoArts** [comment]
Hi!

Google Analytics is not part of the theme, it's installed like any other plugin in the starter for the theme I provide. So you can remove the plugin from the package.json and gatsby-config.js and are good to go :)

**Comment by aleccool213** [comment]
@LekoArts 

Do you know why this google tag manager script is showing up then?

![CleanShot 2020-10-01 at 09 58 23@2x](https://user-images.githubusercontent.com/6475934/94818964-b502bf80-03cc-11eb-9e3f-5e124cf1d3ab.png)

Repo: https://github.com/aleccool213/blog-4

**Comment by aleccool213** [comment]
@LekoArts 

Very weird. When I run the site locally, I dont see it either.

It might be my hosting provider putting it in :( Either Netlify or Cloudflare.

**Comment by aleccool213** [comment]
Turns out I had a Cloudflare app installed which had this script being injected at the DNS level :(

**Comment by LekoArts** [comment]
Well, at least you were able to figure it out :)
