### ISSUE TITLE
[gatsby-starter-minimal-blog]: Language flag for py files in mdx 

### ISSUE THREAD

**Issue by noahsb** [LekoArts/gatsby-themes#514]
## Summary

I'd like to add support for creating code samples in mdx with the .py flag in gatsby-starter-minimal-blog.  Other languages such as jsx, ts already have this - .py files are currently not recognized.  

### Basic example

If we were to use this for jsx, which already exists, we'd write:
``jsx:title=src/components/post.jsx`` followed by the code desired 
I'd like to use _py_ here to add the py flag for code samples

### Motivation

I recognize that I could fork gatsby-themes and add this functionality myself (and if you think it's worth adding I'd be happy to take it on), but I thought it may be useful for others to have as well. It would allow others who use gatsby-starter-minimal-blog to have a py flag for their code.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

There's no need to fork this theme as it's purely a CSS thing. So you could create a `style.css` file and import it in your `gatsby-browser.js` file and be done with it.

If you want you can send in a PR to add more CSS styles like this to the file:

https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/styles/code.ts#L77-L80

On https://prismjs.com/#supported-languages you can see all supported languages. I chose colors that somewhat make sense for the language (e.g. yellow for JS, blue for React as it's their colors) and the color contrast should be good enough (at least AA). There's no need to add all languages though.

**Comment by noahsb** [comment]
Hi Lennart,

I was not aware of the `gatsby-browser.js` API file. My apologies! Yes, I did see that file you mentioned and was thinking that would be the one to require modification. I'd be happy to add a couple of pertinent languages to that file should you find that helpful. Otherwise, I don't want to waste your time (or add useless code to the codebase). I absolutely recognize adding all languages is unnecessary. 

Thanks for all you do - I really admire your work!

**Comment by LekoArts** [comment]
Feel free to send in a PR adding some language that are common :)
