### ISSUE TITLE
Homepage blog limit change

### ISSUE THREAD

**Issue by erayusta** [LekoArts/gatsby-themes#515]
## Summary
Hello,

I want shadow core components or change homepage blog list limit. But it isn't working. local path root/src/@lekoarts/gatsby-theme-minimal-blog-core/components or templates not working. I m searching issue list but i dont see any solution. I am a newbie to gatsby. Please help me this problem?

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to create a new file at `<your-project-root>/src/@lekoarts/gatsby-theme-minimal-blog-core/templates/homepage-query.jsx`:

```jsx
import React from "react"
import { graphql } from "gatsby"
import HomepageComponent from "@lekoarts/gatsby-theme-minimal-blog/src/components/homepage"

const Homepage = ({ data }) => <HomepageComponent posts={data.allPost.nodes} />

export default Homepage

export const query = graphql`
  query($formatString: String!) {
    allPost(sort: { fields: date, order: DESC }, limit: 5) {
      nodes {
        slug
        title
        date(formatString: $formatString)
        excerpt
        timeToRead
        description
        tags {
          name
          slug
        }
      }
    }
  }
`
```

You'll see a warning (that is tracked here https://github.com/gatsbyjs/gatsby/issues/23729) but you can ignore it.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion.
