### ISSUE TITLE
[gatsby-theme-cara] added a navbar, trying to change link color while scrolling

### ISSUE THREAD

**Issue by copocaneta** [LekoArts/gatsby-themes#517]
I built a navbar menu using react-bootstrap into gatsby-theme-cara and I am trying to change the navbar link color while scrolling through the sections, I am completely new to gatsby and react so when I saw [this recommendation](https://stackoverflow.com/questions/60235809/how-to-change-link-navbar-color-while-scrolling-in-react-or-gatsby) I got completely lost.

How do I add componentDidMount to the about section so I can achieve this? (I plan to implement this on the other sections as well).

Any indication would be extremely appreciated.

EDIT: From what I could gather, the About component (and all other components on cara theme), is a stateless functional component (right?) and such won't support lifecycles methods. But I can't for the sake of it figure out how do I convert this component to a stateful component or how do I wrap it in a stateful container so I can use componentDidMount on it.

**Comment by LekoArts** [comment]
Thank you for opening this!

I can only give support for issues related to my themes here as for general React/Gatsby questions there are better places. I recommend heading over to Gatsby's [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions.

`componentDidMount` is still possible in functional stateless components as you can use `useEffect`. The React docs will explain this :)
