### ISSUE TITLE
What is the better way to overwrite field of type in GraphQL schema

### ISSUE THREAD

**Issue by SOHELAHMED7** [LekoArts/gatsby-themes#518]
I use [Forestry](https://forestry.io/) as CMS for my website. Forestry [prefers](https://forestry.io/docs/guides/developing-with-gatsby/#forestry-doesn-t-like-relative-image-urls-gatsby-prefers-them) absolute path and GatsbyJS prefer relative path for image/file/banner image (of a blog post).

Line: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L61 has 

```
banner: File @fileByRelativePath
```

In order to overwrite I put below code in my gatsby-node.js

```js

exports.createSchemaCustomization = ({ actions }) => {
  
  const { createTypes, createFieldExtension } = actions;

  // for fileByAbsolutePath instead of "banner: File @fileByRelativePath"
  createTypes(`
    type MdxPost implements Node & Post {
      slug: String! @slugify
      title: String!
      date: Date! @dateformat
      excerpt(pruneLength: Int = 140): String! @mdxpassthrough(fieldName: "excerpt")
      body: String! @mdxpassthrough(fieldName: "body")
      html: String! @mdxpassthrough(fieldName: "html")
      timeToRead: Int @mdxpassthrough(fieldName: "timeToRead")
      tags: [PostTag]
      banner: File @fileByAbsolutePath(path: "/")   <--- THIS LINE
      description: String
      canonicalUrl: String
    }
  `)
};
```

However my above way is not so much strong to be in sync with upcoming new versions of package `@lekoarts/gatsby-theme-minimal-blog`. I have to manually update the schema here if the new version of `@lekoarts/gatsby-theme-minimal-blog` introduced a new field.

So I would like to know if there is better way to overwrite field of type in GraphQL schema?

If more info needed, please ask.

Thanks.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

This is currently the only way of doing that. But since deleting/changing fields on the schema is a breaking change I'll only do this in major releases. So if it changes, you'll see it :)
