### ISSUE TITLE
How would i clone gatsby gatsby-theme-cara onto my pc? I tried downloading it and installing npm pacakages but i run into error? How would i set it up on my machine? Thanks

### ISSUE THREAD

**Issue by hari-bhandari** [LekoArts/gatsby-themes#536]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

The easiest way to get started with any theme of mine is using the starter, in this case:
https://github.com/LekoArts/gatsby-starter-portfolio-cara

You can clone this repository and are ready to go.

**Comment by hari-bhandari** [comment]
I want to modify the design of the cara.What would be the fastest way to do that?
