### ISSUE TITLE
[gatsby-theme-minimal-blog] Is there a way to remove the hero section from the website?

### ISSUE THREAD

**Issue by rajatguptaa57** [LekoArts/gatsby-themes#540]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by rajatguptaa57** [comment]
So I created an empty hero.mdx -  there is still space between that and the latest Posts section. Can that space be completely removed?

**Comment by LekoArts** [comment]
Hi!

You can either shadow https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/homepage.tsx completely to remove it or update to the latest version of the theme and use the Theme UI config to style the variant "section_hero".

In your Theme UI config this would be at the root:

```js
module.exports = {
  section_hero: {
    display: 'none'
  }
}
```

Then it would be hidden completely.

**Comment by rajatguptaa57** [comment]
Hi,

Thank you for your response and the theme!

**Comment by lwasyl** [comment]
@rajatetc I added the following to `src/gatsby-plugin-theme-ui` (all lowercase) and it seems to work:
```js
import theme from '@lekoarts/gatsby-theme-minimal-blog/src/gatsby-plugin-theme-ui/index'

export default {
  ...theme,
  section_hero: {
    display: 'none'
  },
}

```
