### ISSUE TITLE
How would i customise this theme?

### ISSUE THREAD

**Issue by hari-bhandari** [LekoArts/gatsby-themes#543]
How would i got about customizing this theme? I want to tweak a design ? I tried downloading this repo and installing pacages and i run into error one by other? How would i clone working version of cara? Thanks!I want something like this https://github.com/anuraghazra/anuraghazra.github.io Thanks[

**Comment by LekoArts** [comment]
Hi!

If you want to customize parts of the theme you'll need to shadow files: https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-cara#shadowing
The correct starting point for it would be the corresponding starter.

If you want to learn more about themes itself, read here: https://github.com/LekoArts/gatsby-themes#-learning-gatsby-themes

To your specific enquiry that you want something like anuraghazra/anuraghazra.github.io -- I don't think using a theme is the correct course of action here as the theme has a totally different design. You might be able to use some `-core` themes if you want the underlying GraphQL interfaces and source plugins set up, but I think generally speaking it would be better to start off with a clean plate and not a theme from this repository.
