### ISSUE TITLE
[Jodie]: Instagram tiles in smart phone are too big

### ISSUE THREAD

**Issue by DanArlowski** [LekoArts/gatsby-themes#548]
## Description

As the title suggests - when opening the instagram endpoint on a smartphone - the tiles are too big.

### Steps to reproduce

open every site with the default 
`  grid-template-columns: repeat(auto-fill, minmax(450px, 1fr));` in the `./src/components/style.css`

### Expected result

the tiles should match the size of the screen, and prevent horizontal scrolling

### Actual result

the instagram photos are too big, resulting in a horizontal scrolling in small screens.

### Environment

```
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 14.0
  npmPackages:
    gatsby: ^2.25.3 => 2.27.3 
    gatsby-image: ^2.6.0 => 2.6.0 
    gatsby-plugin-google-analytics: ^2.4.1 => 2.6.0 
    gatsby-plugin-manifest: ^2.5.2 => 2.7.0 
    gatsby-plugin-netlify: ^2.4.0 => 2.6.0 
    gatsby-plugin-offline: ^3.3.3 => 3.5.0 
    gatsby-plugin-sharp: ^2.9.0 => 2.9.0 
    gatsby-plugin-sitemap: ^2.5.1 => 2.7.0 
    gatsby-remark-images: ^3.6.0 => 3.6.0 
    gatsby-source-filesystem: ^2.6.1 => 2.6.1 
    gatsby-source-instagram: ^0.9.0 => 0.9.0 
    gatsby-transformer-remark: ^2.11.1 => 2.11.1 
    gatsby-transformer-sharp: ^2.7.0 => 2.7.0 
  npmGlobalPackages:
    gatsby: 2.27.4
```

## Recommended Fix 
define a last gen small screen smart phone - for example - iphone 6/7/8 and match the `minmax` px attribute to its screen as a default:
it seems that a value of `380px` fixing this issue, without breaking anything in the other screen sizes (macos 15 included), in fact, it makes a 3 tile available in the 15" mac screen which seems even nicer :)

Please give me a go, and i will open a PR in the template repository.

thanks.

Dan

**Comment by LekoArts** [comment]
iPhone 5 goes down to `320px`, so yeah, feel free to send in a PR changing it to `320px` :)

**Comment by DanArlowski** [comment]
@LekoArts 
I've opened a PR,

May I ask - I saw the Instagram tiles are not automatically refreshed, should they or are they supposed to be static?

thanks!

Dan

**Comment by LekoArts** [comment]
They are - as expected - only updated after a new build as they are pulled in from gatsby-source-instagram.
