### ISSUE TITLE
[gatsby-theme-minimal-blog] : How to add a new language to be highlighted in code-blocks?

### ISSUE THREAD

**Issue by gitkalz** [LekoArts/gatsby-themes#563]
Thank you for this great work and excellent theme. 

## Summary

I would like to use additional language support for syntax highlighting , for example HashiCorp Language (hcl) and Powershell.. both of which are supported in prismjs., however I am not sure how could i bring this highlight support into my deployment. 

Steps that I performed so far. 
1) Shadowed the file `code.ts` to `my-site/src/@lekoarts/gatsby-theme-minimal-blog/styles/code.ts` and added the following section

```
    "pre[class~='language-hcl']:before": {
      content: `'hcl'`,
      background: `#f7df1e`,
      color: `black`,
    },
  },
```

I could notice the HCL text appear on the codeblock however I see no highlighting/coloring of the syntax

2) I also attempted to shadow the file `my-site/src/@lekoarts/gatsby-theme-minimal-blog/types.d.ts` and added the languages `hcl` and `powershell`

```
export type Language =
  | "markup"
  | "bash"
.
.
.
  | "yaml"
  | "hcl"
  | "powershell"
```

I do not notice any effect from the above when i run gatsby develop

3) Attempted to shadow src/@lekoarts/gatsby-theme-minimal-blog/components/code.tsx and copied the content from `node_modules`  however I recieve error when gatsby develop as i suspect `.tsx` shadow is not well taken by gatsby

> Please advise a procedure on how to achieve this, I am not a developer by nature so more information/step-by-step (referral links) would help.

### Theme

gatsby-theme-minimal-blog

### Environment (if relevant)

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (1) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^2.25.3 => 2.29.3
    gatsby-plugin-google-analytics: ^2.4.1 => 2.8.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.5.2 => 2.9.1
    gatsby-plugin-netlify: ^2.4.0 => 2.8.0
    gatsby-plugin-offline: ^3.3.3 => 3.7.1
    gatsby-plugin-sitemap: ^2.5.1 => 2.9.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.18
  npmGlobalPackages:
    gatsby-cli: 2.16.2
```

**Comment by LekoArts** [comment]
Hi!

The Code block uses prism-react-renderer: https://github.com/FormidableLabs/prism-react-renderer
Usage in the theme: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/code.tsx

From their [FAQ](https://github.com/FormidableLabs/prism-react-renderer#faq):

> By default prism-react-renderer only includes an arbitrary subset of the languages that Prism supports. You can add support for more by including their definitions from the main prismjs package

And the prop: https://github.com/FormidableLabs/prism-react-renderer#prism

So I'd try shadowing the code file or including the additional languages, and see if it works :)

**Comment by gitkalz** [comment]
Hi Lennart, 

Humbled by your reply, thanks for taking time to help me.. 

I tried to modifying `/my-site/node_modules/@lekoarts/gatsby-theme-minimal-blog/src/components/code.tsx` as below following the guideline from https://github.com/FormidableLabs/prism-react-renderer#prism and issues `gatsby develop` ..

However I couldn't find highlight to my `hcl` code for the example blog content as shown below.

![image](https://user-images.githubusercontent.com/14212713/103997264-d77b5480-51d5-11eb-81e4-ca02e6f5a0e1.png)

```
/* eslint react/destructuring-assignment: 0 */
import React from "react"
import Highlight, { defaultProps } from "prism-react-renderer"
import loadable from "@loadable/component"
import theme from "prism-react-renderer/themes/nightOwl"
import Prism from 'prismjs/components/prism-core';
require('prismjs/components/prism-hcl') 

(typeof global !== "undefined" ? global : window).Prism = Prism;
...
  return (
    <Highlight Prism={Prism} {...defaultProps} code={codeString} language={language} theme={theme}>
      {({ className, style, tokens, getLineProps, getTokenProps }) => (
        <React.Fragment>
          {title && (
            <div className="code-title">
              <div>{title}</div>
            </div>
          )}
...
```

Not sure where I am going wrong and appreciate if someone can help guide.. 

Sorry if I am being too ambitious for a non-developer ( not much idea on front end tech! )..  Appreciate your advice.

**Comment by gitkalz** [comment]
After some experimentation, i figured the following change to above mentioned shadow `code.tsx` helped to get the additional language syntax highlighting to work

```tsx
import Prism from "prism-react-renderer/prism";  /* Import Prism from prism-react-renderer  and not from prismjs-core */
(typeof global !== "undefined" ? global : window).Prism = Prism;
require("prismjs/components/prism-hcl");
...
/* I found its not required to add the Prism prop to be added to Highlight, thus the default would do */

  return (
    <Highlight {...defaultProps} code={codeString} language={language} theme={theme}>
...
```

And lastly dont  forget to add the newly added language to your shadow `code.ts`

```js
    "pre[class~='language-hcl']:before": {
      content: `'hcl'`,
      background: `#f7df1e`,
      color: `black`,
    },
  },
```

Hope this helps someone who plans to extend this awesome theme!

**Comment by LekoArts** [comment]
Great you figured it out -- also thanks for sharing the solution!

**Comment by hurricanehrndz** [comment]
@gitkalz 

You can also add the following  snippet to gabsby-browser.js
'''
import Prism from "prism-react-renderer/prism";
import nixLang from "refractor/lang/nix";
nixLang(Prism);
'''

**Comment by Mombuyish** [comment]
```js
import Prism from 'prism-react-renderer/prism';
import refractor from 'refractor';

import phpLang from 'refractor/lang/php';

Object.setPrototypeOf(refractor, Prism);
refractor.register(phpLang);
```

**Comment by ayhon** [comment]
> You can also add the following snippet to gatsby-browser.js
> 
> ```
> import Prism from "prism-react-renderer/prism";
> import nixLang from "refractor/lang/nix";
> nixLang(Prism);
> ```

The solution from @hurricanehrndz works for me, but if I try to add another language, suddenly my site doesn't load anymore. I have no idea why this is, but how could I add more than one language?

This is what I tried
```js
import Prism from "prism-react-renderer/prism";

// Available completions https://github.com/wooorm/refractor/tree/main/lang
import haskell from "refractor/lang/haskell";
import cpp from "refractor/lang/cpp";

haskell(Prism);
cpp(Prism);
```

**Comment by half0wl** [comment]
@gitkalz's solution worked for me. 

I shadowed `@lekoarts/gatsby-theme-minimal-blog/src/components/code.tsx` with this:
```typescript
import Highlight, { Prism, defaultProps } from "prism-react-renderer"

// @ts-ignore
(typeof global !== "undefined" ? global : window).Prism = Prism;
// Add new languages by `require()`-ing it.
// See https://github.com/PrismJS/prism/tree/master/components for a full list.
require("prismjs/components/prism-php");
```

Here's the full diff of what I did against the current head of main (a51eee00c78eb6a1d4934cc904b24c49263ac2b9):

```diff
--- a/themes/gatsby-theme-minimal-blog/src/components/code.tsx
+++ b/themes/gatsby-theme-minimal-blog/src/components/code.tsx
@@ -1,10 +1,16 @@
 import * as React from "react"
 import { useColorMode } from "theme-ui"
-import Highlight, { defaultProps } from "prism-react-renderer"
+import Highlight, { Prism, defaultProps } from "prism-react-renderer"
 import { calculateLinesToHighlight, getLanguage, GetLanguageInput } from "@lekoarts/themes-utils"
-import Copy from "./copy"
-import useMinimalBlogConfig from "../hooks/use-minimal-blog-config"
-import { lightTheme, darkTheme } from "../utils/prism-themes"
+import Copy from "@lekoarts/gatsby-theme-minimal-blog/src/components/copy"
+import useMinimalBlogConfig from "@lekoarts/gatsby-theme-minimal-blog/src/hooks/use-minimal-blog-config"
+import { lightTheme, darkTheme } from "@lekoarts/gatsby-theme-minimal-blog/src/utils/prism-themes"
+
+// @ts-ignore
+(typeof global !== "undefined" ? global : window).Prism = Prism;
+// Add new languages by `require()`-ing it.
+// See https://github.com/PrismJS/prism/tree/master/components for a full list.
+require("prismjs/components/prism-php");
```

**Comment by ayhon** [comment]
Indeed, I now got it working with shadowing.

Steps I took:
 1. Install `prismjs` with `npm i prismjs`
 2. Create `src/@lekoarts/gatsby-theme-minimal-blog/components/code.tsx`
 3. Add the following code in that file
 ```tsx
import Code from "@lekoarts/gatsby-theme-minimal-blog/src/components/code"
import { Prism } from "prism-react-renderer"

// @ts-ignore
(typeof global !== "undefined" ? global : window).Prism = Prism;
// Add new languages by `require()`-ing it.
// See https://github.com/PrismJS/prism/tree/master/components for a full list.
require("prismjs/components/prism-lua");
require("prismjs/components/prism-haskell");
require("prismjs/components/prism-rust");
require("prismjs/components/prism-cpp");
require("prismjs/components/prism-coq");

export default Code
 ```

I had to add the `import Code` and `export default Code` to properly shadow the file.

**Comment by ap813** [comment]
> Indeed, I now got it working with shadowing.
> 
> Steps I took:
> 
> 1. Install `prismjs` with `npm i prismjs`
> 2. Create `src/@lekoarts/gatsby-theme-minimal-blog/components/code.tsx`
> 3. Add the following code in that file
> 
> ```tsx
> import Code from "@lekoarts/gatsby-theme-minimal-blog/src/components/code"
> import { Prism } from "prism-react-renderer"
> 
> // @ts-ignore
> (typeof global !== "undefined" ? global : window).Prism = Prism;
> // Add new languages by `require()`-ing it.
> // See https://github.com/PrismJS/prism/tree/master/components for a full list.
> require("prismjs/components/prism-lua");
> require("prismjs/components/prism-haskell");
> require("prismjs/components/prism-rust");
> require("prismjs/components/prism-cpp");
> require("prismjs/components/prism-coq");
> 
> export default Code
> ```
> 
> I had to add the `import Code` and `export default Code` to properly shadow the file.

Thank you so much!

**Comment by minhye0k** [comment]
I have read all of the above articles.
Thanks to those who answered.

But all these answers don't work for me now.

Please let me know if you run into the same problem or if you have another solution.

Thank you!
