### ISSUE TITLE
[minimal-blog]: Support querying data from a CMS

### ISSUE THREAD

**Issue by aleccool213** [LekoArts/gatsby-themes#564]
## Summary

I would like to start sourcing content from a self-hosted [Strapi](https://strapi.io/) CMS. Every CMS is different in its API implementation and I think its unrealistic to start supporting some directly. I've had bad experience with Gatsby themes in the past trying to do this. The codebase gets really ugly. 

Having a document to at least get people started in implementing their own CMS into this theme would be super useful 👍🏻 

### Basic example

* run gatsby build
* blog posts are queried from a self-hosted strapi cms instance (bonus, pages are queried as well)

### Motivation

Personally, I want to start writing my blog posts in the new year. Having a CMS to just write blog posts in is helpful for me as I dont need to muck around with the code base. I usually get distracted when I do this and want to upgrade everything lol

**Comment by phatpham9** [comment]
any progress? I want to use github issues system as my blog cms, tried to modify it but got no luck

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

There's not really a long written guide on this topic, but here's an example repository: https://github.com/LekoArts/minimal-blog-yaml

The really important bit is this here:
https://github.com/LekoArts/minimal-blog-yaml/blob/2820b68dc1810a15b514394868c4a860e2865532/gatsby-node.js#L1-L25

You'll need to create a new `type` e.g. `StrapiPost` and implement it to the generic `Post` interface. In the `onCreateNode` step you'll then need to adapt the incoming node shape to the `Post` shape.

This isn't ideal so another way would be to just copy the two folders from https://github.com/LekoArts/gatsby-themes/tree/master/themes and run it locally (without publishing) as a `yarn workspace`. You'd then have essentially forked the theme but you can directly edit the `gatsby-node.js` of the `-core` theme.
