### ISSUE TITLE
How do I rename the "Blog" page?

### ISSUE THREAD

**Issue by allardbrain** [LekoArts/gatsby-themes#565]
## Summary
Thank you for a beautiful theme!

I would like to rename the "Blog" page to "Essays". Which files and variables would I need to change to accomplish this?

## Relevant information

I read this, but I don't need to create a new page, just need to rename the Blog page.
- https://github.com/LekoArts/gatsby-themes/issues/370

### Theme

gatsby-theme-minimal-blog

### Environment (if relevant)

```
 System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.11 - /usr/local/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 50.1.0
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.20.36 => 2.24.51
    gatsby-plugin-google-analytics: ^2.1.4 => 2.3.13
    gatsby-plugin-manifest: ^2.2.3 => 2.4.25
    gatsby-plugin-netlify: ^2.1.3 => 2.3.13
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sitemap: ^2.2.19 => 2.4.12
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.10 => 1.1.12
  npmGlobalPackages:
    gatsby-cli: 2.12.89
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

You'll want to shadow the blog page ([notice in the readme](https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog#shadowing)) and explanation of it in the docs: https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/

So in practice this means:

1) Create a file at `src/@lekoarts/gatsby-theme-mimimal-blog/components/blog.jsx` (you'll need to create the folders if they don't exist yet)
2) This way you'll shadow the source file: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/blog.tsx
3) As the source file is written in TypeScript and relies on relative imports, some changes are needed. Your file should look like this:

```jsx
/** @jsx jsx */
import { jsx, Heading, Link as TLink } from "theme-ui"
import { Link } from "gatsby"
import { Flex } from "@theme-ui/components"
import Layout from "@lekoarts/gatsby-theme-minimal-blog/src/components/layout"
import Listing from "@lekoarts/gatsby-theme-minimal-blog/src/components//listing"
import useMinimalBlogConfig from "@lekoarts/gatsby-theme-minimal-blog/src/hooks/use-minimal-blog-config"
import replaceSlashes from "@lekoarts/gatsby-theme-minimal-blog/src/utils/replaceSlashes"
import SEO from "@lekoarts/gatsby-theme-minimal-blog/src/components/seo"

const Blog = ({ posts }) => {
  const { tagsPath, basePath } = useMinimalBlogConfig()

  return (
    <Layout>
      <SEO title="Blog" />
      <Flex sx={{ alignItems: `center`, justifyContent: `space-between`, flexFlow: `wrap` }}>
        <Heading as="h1" variant="styles.h1" sx={{ marginY: 2 }}>
          Essays
        </Heading>
        <TLink
          as={Link}
          sx={{ variant: `links.secondary`, marginY: 2 }}
          to={replaceSlashes(`/${basePath}/${tagsPath}`)}
        >
          View all tags
        </TLink>
      </Flex>
      <Listing posts={posts} sx={{ mt: [4, 5] }} />
    </Layout>
  )
}

export default Blog
```
