### ISSUE TITLE
Regarding `navigation` and `externalLinks`

### ISSUE THREAD

**Issue by shifuchen98** [LekoArts/gatsby-themes#566]
## Summary

Is there a difference between changing `navigation` and `externalLinks` under `options` of the `@lekoarts/gatsby-theme-minimal-blog` plugin and `siteMetadata`? In the [examples](https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog#example-usage) shown in `README.md`, both two places are accepting `navigation` and `externalLinks`.

### Theme

[@lekoarts/gatsby-theme-minimal-blog](https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog)

**Comment by LekoArts** [comment]
Thanks! The items in `siteMetadata` were outdated so I removed them :)
