### ISSUE TITLE
Cara Theme: Markdown files missing

### ISSUE THREAD

**Issue by OliverHuntsman** [LekoArts/gatsby-themes#574]
## Description

In the sections there is only one markdown file for editing and not 4, I checked the repository and it is the same here

### Steps to reproduce

I cloned the repository and opened up the files
The repository I cloned was this one
https://github.com/LekoArts/gatsby-starter-portfolio-cara

should this repository be cloned instead?
https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-cara
### Expected result

As per the ReadMe there should be some markdown files to edit

### Actual result

No markdown files were available to edit

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.96
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.25.3 => 2.31.1 
    gatsby-plugin-google-analytics: ^2.4.1 => 2.10.0 
    gatsby-plugin-manifest: ^2.5.2 => 2.11.0 
    gatsby-plugin-netlify: ^2.4.0 => 2.10.0 
    gatsby-plugin-offline: ^3.3.3 => 3.9.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.20 
  npmGlobalPackages:
    gatsby-cli: 2.18.0
    gatsby-starter-netlify-cms: 1.1.3

**Comment by LekoArts** [comment]
Hi, thanks for using the theme!

[The README says](https://github.com/LekoArts/gatsby-starter-portfolio-cara#changing-content) that in the theme itself four files are defined which you can override. One example override is here: https://github.com/LekoArts/gatsby-starter-portfolio-cara/blob/master/src/%40lekoarts/gatsby-theme-cara/sections/intro.mdx

If you wish to override the other sections you'll need to create the files in the same directory.

**Comment by OliverHuntsman** [comment]
That's great thank you, all makes sense & figured it out

I've just used the theme here:-

Consult369.com
