### ISSUE TITLE
[minimal-blog]: Image aspect ratios distorted

### ISSUE THREAD

**Issue by kuzdogan** [LekoArts/gatsby-themes#577]
## Description

If the added images are vertical, they get stretched horizontally to fit into a square. I wasn't able to figure out why this is the case.

### Steps to reproduce

An example is available in this [post](http://kaanuzdogan.com/i-wore-a-continious-glucose-monitor-for-2-weeks) very below in the test image.

The repo is available [here](https://github.com/kuzdogan/kuzdogan-personal-site). Note that previously in [this post](https://kaanuzdogan.com/avoid-updating-your-xiaomi-mi-a-3-to-android-11-for-now) the image did not get distorted. 

### Expected result

Images keep aspect ratio

### Actual result

The vertical image gets stretched into a square

### Environment

```

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    npm: 6.11.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0.1
  npmPackages:
    gatsby: ^2.31.1 => 2.31.1 
    gatsby-plugin-disqus: ^1.2.2 => 1.2.2 
    gatsby-plugin-google-analytics: ^2.4.1 => 2.6.0 
    gatsby-plugin-google-gtag: ^2.3.0 => 2.3.0 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^2.5.2 => 2.7.0 
    gatsby-plugin-mdx: ^1.10.0 => 1.10.0 
    gatsby-plugin-netlify: ^2.4.0 => 2.6.0 
    gatsby-plugin-offline: ^3.3.3 => 3.5.0 
    gatsby-plugin-sitemap: ^2.5.1 => 2.7.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.17 
    gatsby-remark-images: ^3.11.0 => 3.11.0 
  npmGlobalPackages:
    gatsby-cli: 2.14.1
```

Optionally I'd also like to impose a `max-height` but this also breaks the aspect ratio in applied in `wrapperStyle` of the `gatsby-remark-images`.

**Comment by LekoArts** [comment]
Hi!

I've published a new version of the theme with Gatsby v3 support (and all updated versions of other plugins). If you're still seeing this with the new version, please let me know here. Thanks!
