### ISSUE TITLE
Remove Footer

### ISSUE THREAD

**Issue by ShreyaanVashishtha** [LekoArts/gatsby-themes#583]
How do I remove the footer?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Please see the previously answered questions for this. Thanks
https://github.com/LekoArts/gatsby-themes/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+footer+label%3A%22type%3A+question+or+discussion%22
