### ISSUE TITLE
(How/is it possible) to shadow cara.tsx without shadowing everyother .tsx that needs to be imported?

### ISSUE THREAD

**Issue by shaunkorba** [LekoArts/gatsby-themes#584]
I have been racking my brain reading over the shadowing documentation, but I just can't find the answer to this question, **I'm sorry if it is a stupid one...**

I have set up a site using LekoArts' gastby-theme cara

I understand that what I create in the theme folder (src/@lekoarts/gatsby-theme-cara) will shadow the files seen in the theme's src folder. Which can be viewed here on github:

What I want to do is shadow just the "templates/cara.tsx" file, there I want to increase the size of the projects section to make room for the extra project-cards I have on my site.

![image](https://user-images.githubusercontent.com/24483299/111087338-6c147280-84f7-11eb-8694-c7ebac7d35c1.png)

The issue is that that .tsx file has many other components that need to be imported that I don't want to shadow. 

**How do I import these files that are on the theme's src directory (without having to shadow them all locally)?**

**Comment by LekoArts** [comment]
Hi!

You can import them from the npm package, e.g.

```js
import Layout from "@lekoarts/gatsby-theme-cara/components/layout"
```

**Comment by shaunkorba** [comment]
Thanks so much, I tried something so close to that but couldn't get it right!
