### ISSUE TITLE
[gatsby-started-minimal-blog]: Can't succesfully create a new project using `gatsby new`

### ISSUE THREAD

**Issue by grian32** [LekoArts/gatsby-themes#585]
## Description

When I try to run this command copy pasted from `https://www.gatsbyjs.com/starters/LekoArts/gatsby-starter-minimal-blog/` with only the project name changed it errors out during npm install: `gatsby new blog https://github.com/LekoArts/gatsby-starter-minimal-blog`

### Steps to reproduce

- Run the command `gatsby new blog https://github.com/LekoArts/gatsby-starter-minimal-blog`
- Wait for it to error.

### Expected result

It should make a new project succesfully and install dependencies without any problems.

### Actual result

It erorrs out during the installing dependencies part.

### Environment

  System:
    OS: Linux 5.8 Pop!_OS 20.04 LTS
    CPU: (4) x64 Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    npm: 7.5.3 - ~/.nvm/versions/node/v14.8.0/bin/npm
  npmGlobalPackages:
    gatsby-cli: 3.1.0

**Comment by LekoArts** [comment]
Hi!

That's not an issue with the starter but with your local setup. I see you  use npm 7 so maybe the peerDependencies are missing.

You can clone the starter and then manually install the dependencies with `npm install ----legacy-peer-deps`. If that doesn't help please ask here: https://github.com/gatsbyjs/gatsby/discussions/categories/help

**Comment by grian32** [comment]
Downgrading to npm 6 seems to have fixed the issue, thanks.
