### ISSUE TITLE
How to add a custom about me text?

### ISSUE THREAD

**Issue by DavideVito** [LekoArts/gatsby-themes#588]
## Summary
Hi, I've run this command as specified [here](https://github.com/LekoArts/gatsby-themes/tree/master/examples/emilia#-getting-started) guide. 

But I cannot find a way to add a custom about me, in the guide you say to: "Create a file at src/@lekoarts/gatsby-theme-emilia/texts/about-me.mdx to edit the text.", but I cannot find the "src" folder.

Am I doing something wrong?

## Relevant information

Here is my folder structure:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/47363438/115608205-42185200-a2e6-11eb-92d6-f3737bd720ce.png">

### Theme

[emilia](https://github.com/LekoArts/gatsby-themes/tree/master/examples/emilia#-getting-started)

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.85
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.25.3 => 2.32.12 
    gatsby-plugin-gatsby-cloud: ^1.0.1 => 1.0.2 
    gatsby-plugin-google-analytics: ^2.4.1 => 2.11.0 
    gatsby-plugin-manifest: ^2.5.2 => 2.12.1 
    gatsby-plugin-netlify: ^2.4.0 => 2.11.1 
    gatsby-plugin-offline: ^3.3.3 => 3.10.2 
    gatsby-plugin-sitemap: ^2.5.1 => 2.12.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.22 
  npmGlobalPackages:
    gatsby-cli: 3.3.0

### File contents (if changed)

`gatsby-node.js`: not present
`gatsby-browser.js`: not present
`gatsby-ssr.js`: not present

**Comment by LekoArts** [comment]
Hi!

You'll need to create the folders on your own to shadow files. This is also explained in more detail in the linked guide: https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/

So simply create the folder structure `src/@lekoarts/gatsby-theme-emilia/texts` and place a `about-me.mdx` in it.
