### ISSUE TITLE
[minimal-blog]: TypeError: Cannot read property 'title' of null

### ISSUE THREAD

**Issue by strdr4605** [LekoArts/gatsby-themes#589]
## Description

I start writing the post and I can see the result in the browser. But after some time I start getting this error

![image](https://user-images.githubusercontent.com/16056918/115958225-38256780-a50f-11eb-8656-3170a09daff5.png)

### Steps to reproduce

While creating a new `content/posts/new-post/index.mdx` file for a new post. I run `gatsby develop` and start writing the post. 

I add the front matter:

```md
---
title: My title
slug: my-slug
date: 2021-03-28
description: desc
tags:
  - my-tag
---

# Post content
```

And then start typing the post content.

----

Here is the repo and that post that you may try to edit to get this issue:
https://github.com/strdr4605/strdr4605.github.io/blob/source/content/posts/35-hackathons/index.mdx

Also, the error is only for the current post that is edited. Other pages are working correctly (including other posts).

I suspect that it may happen when I edit again the file and the build for development is interrupted.
The only way to fix the issue is to restart the server.

**NOTE:** It's worth mentioning that I did some adjustments to [post.tsx](https://github.com/strdr4605/strdr4605.github.io/blob/source/src/components/post.tsx). But I don't think that my changes can cause this issue because I can reproduce it with default post component.

### Expected result

GatsbyJS should build the page without any errors.

### Actual result

`TypeError: Cannot read property 'title' of null` for the currently edited page in markdown.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 90.0.4430.85
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.20.36 => 2.24.55
    gatsby-plugin-google-analytics: ^2.1.4 => 2.3.13
    gatsby-plugin-manifest: ^2.2.3 => 2.4.28
    gatsby-plugin-my-social-cards: file:plugins/gatsby-plugin-my-social-cards => 0.0.1
    gatsby-plugin-netlify: ^2.1.3 => 2.3.14
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sass: ^2.3.12 => 2.3.12
    gatsby-plugin-sitemap: ^2.2.19 => 2.4.12
    gatsby-remark-autolink-headers: ^2.3.12 => 2.3.12
  npmGlobalPackages:
    gatsby-cli: 2.12.52
```

**Comment by LekoArts** [comment]
Hi!

I've published a new version of the theme with Gatsby v3 support (and all updated versions of other plugins). If you're still seeing this with the new version, please let me know here. Thanks!
