### ISSUE TITLE
Changing /blog navigation

### ISSUE THREAD

**Issue by ryan-hong** [LekoArts/gatsby-themes#590]
## Summary

Is there a way to change the default "/blog" in gatsby-config.js to a different name such as "/experience"?  The content will be the same, but I want to change the URL to something that makes more sense.   

So instead of:
```
 navigation: [
          {
            title: `Blog`,
            slug: `/blog`,
          },
```

I want:
```
navigation: [
          {
            title: `Work Experience`,
            slug: `/experience`,
          },
```

**Comment by ryan-hong** [comment]
I figured out how to change it.   I shadowed `default-options.js` in `gatsby-theme-minimal-blog-core` and changed the path there.  Is this the correct way to do it?  Would it matter that `blogPath` is no longer /blog but rather /experience?

**Comment by LekoArts** [comment]
Hi!

You should use the `blogPath` option on the theme: https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog#theme-options (if you only use the `-core` theme then on that theme options object).
