### ISSUE TITLE
[minimal-blog]: gatsby develop broken 

### ISSUE THREAD

**Issue by CryptoGrogu** [LekoArts/gatsby-themes#593]
## Description

First of all we have multiple vulnerabilities in old dependancies that are being used, but also the project can't be developed 

### Steps to reproduce

Followed the ReadMe guide,
gatsby new project-name https://github.com/LekoArts/gatsby-starter-minimal-blog
cd project-name
gatsby develop
 

### Expected result

Blog to launch locally 

### Actual result

gatsby develop                                                                 
/Users/sathosi/Developer/project-name/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module '@reach/router/lib/utils'
Require stack:
- /Users/sathosi/Developer/project-name/node_modules/gatsby/dist/utils/find-page-by-path.js
- /Users/sathosi/Developer/project-name/node_modules/gatsby/dist/utils/websocket-manager.js
- /Users/sathosi/Developer/project-name/node_modules/gatsby/dist/utils/page-data.js
- /Users/sathosi/Developer/project-name/node_modules/gatsby/dist/utils/webpack-status.js
- /Users/sathosi/Developer/project-name/node_modules/gatsby/dist/commands/develop-process.js
- /Users/sathosi/Developer/project-name/.cache/tmp-31161-JJvB451u5tms
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sathosi/Developer/project-name/node_modules/gatsby/src/utils/find-page-by-path.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sathosi/Developer/project-name/node_modules/gatsby/dist/utils/find-page-by-path.js',
    '/Users/sathosi/Developer/project-name/node_modules/gatsby/dist/utils/websocket-manager.js',
    '/Users/sathosi/Developer/project-name/node_modules/gatsby/dist/utils/page-data.js',
    '/Users/sathosi/Developer/project-name/node_modules/gatsby/dist/utils/webpack-status.js',
    '/Users/sathosi/Developer/project-name/node_modules/gatsby/dist/commands/develop-process.js',
    '/Users/sathosi/Developer/project-name/.cache/tmp-31161-JJvB451u5tms'
  ]
}

### Environment

  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    npm: 7.13.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.1
  npmGlobalPackages:
    gatsby-cli: 3.4.0

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

> First of all we have multiple vulnerabilities in old dependancies that are being used

While those audit messages might seem scary it doesn't show the full picture of the individual package is affected as they are not sophisticated enough to check the actual code. While the theme is still on Gatsby v2 (and I'm in the process of updating it), I want to highlight that those messages won't affect your finished site as nothing of that is run on the client, only during development. You can ignore those as they are not relevant to Gatsby.

I've successfully followed the steps and my E2E Tests + the live website (https://minimal-blog.lekoarts.de/) work so I know that the theme is not broken.

```shell
Development/GitHub
➜ gatsby new project-name https://github.com/LekoArts/gatsby-starter-minimal-blog

info Creating new site from git: https://github.com/LekoArts/gatsby-starter-minimal-blog.git

Cloning into 'project-name'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 37 (delta 1), reused 22 (delta 0), pack-reused 0
Receiving objects: 100% (37/37), 1.74 MiB | 6.93 MiB/s, done.
success Created starter directory layout
info Installing packages...

yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.20.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "gatsby > eslint-plugin-graphql > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
warning "gatsby-plugin-gatsby-cloud > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
[4/4] Building fresh packages...
info Initialising git in project-name

info Create initial git commit in project-name
info
Your new Gatsby site has been successfully bootstrapped. Start developing it by running:

  cd project-name
  gatsby develop



Development/GitHub took 2m 7s
➜ cd project-name

project-name on  main is 📦 v1.3.10 via ⬢ v14.16.1
➜ gatsby develop
success open and validate gatsby-configs - 0.162s
success load plugins - 2.838s
success onPreInit - 0.042s
success initialize cache - 0.008s
success copy gatsby files - 0.536s
success onPreBootstrap - 0.032s
success createSchemaCustomization - 0.009s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.698s
success building schema - 0.340s
info Total nodes: 93, SitePage nodes: 13 (use --verbose for breakdown)
success createPages - 0.073s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.059s
success update schema - 0.019s
success write out redirect data - 0.007s
success Build manifest and related icons - 0.005s
success onPostBootstrap - 0.015s
info bootstrap finished - 9.230s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.563s
success write out requires - 0.043s
success run static queries - 0.040s - 2/2 49.75/s
success run page queries - 0.696s - 2/2 2.87/s
⠀
You can now view minimal-blog in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 13.206s
```

npm 7 and it's new behavior regarding to `peerDependencies` is the culprit here. See this SO for explanation: https://stackoverflow.com/a/66620869/10164092

If you don't want to use yarn (as I do) you can workaround this by cloning the starter and installing dependencies with a flag:

```shell
git clone git@github.com:LekoArts/gatsby-starter-minimal-blog.git
cd gatsby-starter-minimal-blog
npm install --legacy-peer-deps
npm run develop
```
