### ISSUE TITLE
.MDX files are not overwriting default content (just intro.mdx)

### ISSUE THREAD

**Issue by jaimeagudo** [LekoArts/gatsby-themes#677]
## Description

.MDX files are not overwriting default content on https://github.com/LekoArts/gatsby-starter-portfolio-cara#changing-content, just changes on the `intro.mdx` are reflected

### Steps to reproduce

Follow https://github.com/LekoArts/gatsby-starter-portfolio-cara#changing-content to overwrite `projects.mdx`
Example: https://github.com/jaimeagudo/www-aci

I tried kiling and restarting `npm run develop` and even `npm run build`

### Expected result

Templates content overwrites default content

### Actual result

Only the intro.mdx changes are reflected live (in 2s aprox), no other sections are affected. 

### Environment
```
  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.24.0 - /opt/homebrew/bin/npm
  Languages:
    Python: 3.8.5 - /Users/jaime.agudo/.pyenv/shims/python
  Browsers:
    Firefox: 78.12.0
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.6.1 => 3.13.0
    gatsby-plugin-gatsby-cloud: ^2.6.1 => 2.11.0
    gatsby-plugin-google-analytics: ^3.6.0 => 3.13.0
    gatsby-plugin-manifest: ^3.6.0 => 3.13.0
    gatsby-plugin-netlify: ^3.6.1 => 3.13.0
    gatsby-plugin-offline: ^4.6.0 => 4.13.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.24
  npmGlobalPackages:
    gatsby: 3.14.0
```

**Comment by AdamWorley** [comment]
If you've already run gatsby to generate the website e.g. `gatsby develop` before adding in the override .mdx file you'll need to run `gatsby clean` and then run the build again

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

As Adam said you might need to do a `gatsby clean` (although locally this wasn't necessary for me). Anyways, the shadowing itself works and other people have successfully shadowed those files without changing the project itself :)
