### ISSUE TITLE
[minimal blog]: TimeToRead is always set to 1 min

### ISSUE THREAD

**Issue by ldlac** [LekoArts/gatsby-themes#731]
## Description

Hi, I'm probably missing something, I couldn't find a line in the readme mentioning the time to read.
I'm trying to define the time to read of my posts but they are always equal to 1, even if they are suppose to be nullable.
Am I missing something caused by `@mdxpassthrough` on this field?

Issue is in the [minimal blog theme](https://github.com/LekoArts/gatsby-starter-minimal-blog)

### Steps to reproduce

Create a index.mdx in a subfolder of /posts with a timeToRead set to a given value. In this case, 10

```
---
...
timeToRead: 10
---

...
```

### Expected result

Should display given timeToRead value, in this case, `10 min read`

If the given timeToRead is not present in the index.mdx, it should not be visible at all according to these lines

https://github.com/LekoArts/gatsby-themes/blob/main/themes/gatsby-theme-minimal-blog/src/components/post.tsx
```
{post.timeToRead && ` — `}
{post.timeToRead && <span>{post.timeToRead} min read</span>}
```

### Actual result

TimeToRead is always 1

### Environment

  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
  Binaries:
    Node: 14.17.6 - ~\AppData\Local\Temp\yarn--1636949005774-0.5825950746373543\node.CMD
    Yarn: 1.16.0 - ~\AppData\Local\Temp\yarn--1636949005774-0.5825950746373543\yarn.CMD
    npm: 7.23.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.7
  Browsers:
    Chrome: 95.0.4638.69
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53)
  npmPackages:
    gatsby: ^4.0.0 => 4.1.4 
    gatsby-omni-font-loader: ^1.3.1 => 1.3.3 
    gatsby-plugin-feed: ^4.0.0 => 4.1.1 
    gatsby-plugin-gatsby-cloud: ^4.0.0 => 4.1.2 
    gatsby-plugin-manifest: ^4.0.0 => 4.1.3 
    gatsby-plugin-sitemap: ^5.0.0 => 5.1.1 
    gatsby-plugin-theme-ui: ^0.12.0 => 0.12.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.26

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

The `timeToRead` is not something you'd define but that gets calculated by `gatsby-plugin-mdx`:

https://github.com/gatsbyjs/gatsby/blob/2be4beabfc8ce134fa6adca92e969a5126e6a1d8/packages/gatsby-plugin-mdx/gatsby/create-schema-customization.js#L266-L279

If for you it's always 1 you might have content that the plugin can't parse or it's a language that it can't parse. But that's out of the scope of this theme and something for Gatsby itself.

**Comment by ldlac** [comment]
Oh makes sense, I got confused with the nullable part. So in fact, timeToRead is computed and cannot be nullable at all?

**Comment by LekoArts** [comment]
In the case of MDX it won't be null at any time, yes (defaults to 1). But back then when I wrote this I think I wrote it this way to account for cases where the data source is different and it would possibly not exist. But with the default usage of the theme you don't have to worry about that.

**Comment by ChangerHe** [comment]
Maybe Make `timeToRead` to optional is also a good solution.
Until now, `gatsby-plugin-mdx` had not solved the problem where `timeToRead` is always 1 when use Chinese or Japanese in `mdx`
