### ISSUE TITLE
Have a ProjectCard open a simple html page in the directory

### ISSUE THREAD

**Issue by shaunkorba** [LekoArts/gatsby-themes#736]
### Discussed in https://github.com/LekoArts/gatsby-themes/discussions/735

<div type='discussions-op-text'>

<sup>Originally posted by **shaunkorba** November 24, 2021</sup>
I want to have one of my project cards link to an html file within the project directory (a basic html file with some JavaScript) this is to showcase a JavaScript project I developed.

I'm entering my links within the "projects.mdx" file within "src/gatsby-theme-cara/sections/projects.mdx" inside: 
(ProjectCard link="HERE")

I'm not sure how to write this link to open an html file in the src folder of the project directory I've tried a few times to use paths like "src/visualizer/dancingPaint.html" but they all have given me 404.

Is it possible to have a gatsby site open a plain html file in the project directory? 

Where do you suggest I place an html file like this and have a project card open it?  

Thank you for the help</div>

**Comment by LekoArts** [comment]
Please use the discussion, that's what it's for, thanks.
