### ISSUE TITLE
Is there an easy way to change the avatar.png header image? 

### ISSUE THREAD

**Issue by stealthkk** [LekoArts/gatsby-themes#77]
No matter what I try I can't override it with shadowing. I know I could probably inherit and override the header class but I'm trying to avoid that because it seems wasteful.

**Comment by LekoArts** [comment]
Thanks for the issue! This was an error by me, I forgot that you won't be able to shadow that file. You now can place an image called `avatar` into `content/assets` and it'll be replaced by yours.

**Comment by simonpeterdebbarma** [comment]
Hi @LekoArts, I didn't want to open an issues page as this was already solved, but do you see any errors?

![image](https://user-images.githubusercontent.com/31207418/77836575-02039180-711d-11ea-89e1-b92d1082e8be.png)

![image](https://user-images.githubusercontent.com/31207418/77836587-19427f00-711d-11ea-939e-0b828aa91b57.png)

![image](https://user-images.githubusercontent.com/31207418/77836592-265f6e00-711d-11ea-96ec-90f199e4ab30.png)
