### ISSUE TITLE
[gatsby-starter-portfolio-cara]: Footer frequently not rendered

### ISSUE THREAD

**Issue by xiazeyu** [LekoArts/gatsby-themes#798]
## Description

I'm now using Gatsby Starter Portfolio: Cara, and when I visit my page and the [official demo](https://cara.lekoarts.de/).

The footer component is not rendered frequently. This problem is also for my [profile page](https://xiaze.top/) with [code](https://github.com/xiazeyu/xiaze_main).

After I tried resize the window, and do some selecting, the footer appears.

It is confirmed that this is not due to network issue, and the footer component did appear in the DevTools of Chrome and Edge.

See screenshots below.

The correct appearance is really important for me due to censor requirements in my country.

### Steps to reproduce

I entered the [official demo](https://cara.lekoarts.de/), and scrolled down to the footer.

### Expected result

The footer should render like this.
![Snipaste_2022-01-29_16-41-43](https://user-images.githubusercontent.com/10560038/151654303-c4dd5143-f639-429b-b6e9-55ae246ca0cc.png)

### Actual result

Most of the time, the footer renders like this.
![Snipaste_2022-01-29_16-28-01](https://user-images.githubusercontent.com/10560038/151654326-a8dfff9a-1972-4f93-a944-5c1651bc86ee.png)

The footer component appears in the DevTool:
![image](https://user-images.githubusercontent.com/10560038/151654352-e71b5216-8f4c-48f4-b307-fbc6083829f8.png)

Sometime the component is like this.
![image](https://user-images.githubusercontent.com/10560038/151654366-1069cdd6-85ad-49b0-8771-66ade84af177.png)

If I drag around the footer area, or resize the window, the full footer appears.
![image](https://user-images.githubusercontent.com/10560038/151654386-3871b143-6a99-469f-9857-474c3e75730d.png)

I also tried no-cache and private mode, and the problem still exists.

### Environment

I'm now using Google Chrome 97.0.4692.99(latest) and Microsoft Edge 97.0.1072.76 on Windows 11 (Dev 22543.1000) with NVIDIA Geforce GTX 1080 on 1920x1080 resolution.

The problems appers both in fullscreen mode and windows mode.

**Comment by xiazeyu** [comment]
Some workaround:

change `themes/gatsby-theme-cara/src/templates/cara.tsx`:

from

```jsx
const Cara = () => (
  <Layout>
    <Parallax pages={5}>
      <Hero offset={0} factor={1} />
      <Projects offset={1} factor={2} />
      <About offset={3} factor={1} />
      <Contact offset={4} factor={1} />
    </Parallax>
  </Layout>
)
```

to

```jsx
const Cara = () => (
  <Layout>
    <Parallax pages={4}>
      <Hero offset={0} factor={1} />
      <Projects offset={1} factor={1} />
      <About offset={2} factor={1} />
      <Contact offset={3} factor={1} />
    </Parallax>
  </Layout>
)
```

That works fine for me.

It seems to me that the `pages={5}` designing method is not working well with the footer.

**Comment by LekoArts** [comment]
Hi!

Please open a bug report at https://github.com/pmndrs/react-spring/issues to first make sure that this is not an upstream issue. Thanks!
