### ISSUE TITLE
[gatsby-theme-emilia]: Improve text-align of title in Card

### ISSUE THREAD

**Issue by torn4dom4n** [LekoArts/gatsby-themes#983]
## Description

If the title is too long, it won't be the center.

### Steps to reproduce

- Add a project with a long title
- Run Gatsby build and see it

### Expected result

Text-align is the center.

![image](https://user-images.githubusercontent.com/27698189/188413044-4b9833b5-5358-4ccd-b7bc-75c165c2ed21.png)

### Actual result

![image](https://user-images.githubusercontent.com/27698189/188412887-06795c09-20db-46e7-94e6-021a473b0f4c.png)

**Comment by LekoArts** [comment]
Thanks! Will be fixed with https://github.com/LekoArts/gatsby-themes/pull/987
