### ISSUE TITLE
[@lekoarts/gatsby-theme-cara]: /sections/projects.mdx: Identifier '_frontmatter' has already been declared. (2:13)

### ISSUE THREAD

**Issue by eniger31** [LekoArts/gatsby-themes#988]
## Description

Hi @LekoArts , I do not have access to the sources to modify this problem. can you please help me? 
### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

correct gastby develop command

### Actual result
`ERROR

/Users/Regine/GATSBY/gatsby-starter-portfolio-cara/src/@lekoarts/gatsby-theme-cara/sections/projects.mdx: Identifier '_frontmatter' has already been declared. (2:13)

1 | export const _frontmatter = {};

2 | export const _frontmatter = {}
| ^

SyntaxError: /Users/Regine/GATSBY/gatsby-starter-portfolio-cara/src/@lekoarts/gatsby-theme-cara/sections/projects.mdx: Identifier '_frontmatter' has already been declared. (2:13)
1 | export const _frontmatter = {};

2 | export const _frontmatter = {}
| ^`

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    npm: 8.5.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.6.1
  npmPackages:
    gatsby: ^4.18.2 => 4.22.1
    gatsby-plugin-gatsby-cloud: ^4.18.1 => 4.22.0
    gatsby-plugin-manifest: ^4.18.1 => 4.22.0
    gatsby-plugin-mdx: ^3.20.0 => 3.20.0
    gatsby-plugin-theme-ui: ^0.14.7 => 0.14.7
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.27 => 1.1.27
  npmGlobalPackages:
    gatsby-cli: 4.22.1

**Comment by LekoArts** [comment]
This is a user error on your end, please stick to https://github.com/LekoArts/gatsby-themes/discussions/985

**Comment by eniger31** [comment]
🖤 Thank you @LekoArts  . this is my repository https://github.com/RG31/gatsby-starter-portfolio-cara.git
